<?php
/*
 * Copyright (C) 2008-2013 e107 Inc (e107.org), Licensed under GNU GPL (http://www.gnu.org/licenses/gpl.txt)
 *
 * Admin Language File
 *
*/
define("BANLAN_2", "Nav aizliegumu sarakstā.");
define("BANLAN_3", "Esošie Aizliegumi");
define("BANLAN_5", "Ievadi IP, e-pastu vai hostu");
define("BANLAN_7", "Iemesls");
define("BANLAN_8", "Aizlieguma adrese");
define("BANLAN_9", "Bloķēt lietotājus no vietnes pa e-pastu, IP vai uzņēmējas adresi");
define("BANLAN_10", "IP / e-pasts / iemesls");
define("BANLAN_11", "Automātiska aizliegšana: vairāk nekā 10 neizdevušies pieteikšanās mēģinājumi");
define("BANLAN_12", "Piezīme: reversā DNS pašlaik ir atspējota; tai jābūt iespējotai, lai atļautu aizliegumu ar uzņēmēju. Bloķēšana ar IP un e-pasta adresi joprojām funkcionēs normāli.");
define("BANLAN_13", "Piezīme. Lai aizliegtu lietotāju pēc lietotāja vārda, dodieties uz lietotāju administrācijas lapu:");
define("BANLAN_14", "Aizlieguma saraksts");
define("BANLAN_15", "Ziņojumi / Aizlieguma periodi");
define("BANLAN_16", "Aizliegšana");
define("BANLAN_17", "Aizlieguma Datums");
define("BANLAN_18", "Aizliegumi Beigušies");
define("BANLAN_19", "Piezīme");
define("BANLAN_20", "Tips");
define("BANLAN_22", "Nezināms");
define("BANLAN_23", "diena-(s)");
define("BANLAN_24", "stundas");
define("BANLAN_25", "Pievienot Aizlieguma sarakstam");
define("BANLAN_26", "Esošie");
define("BANLAN_27", "Neizmantotās IP adreses apzīmētas ar zīmēm - tagad:");
define("BANLAN_28", "Aizlieguma Tips");
define("BANLAN_29", "Ziņa, kas jāparāda aizliegtajam lietotājam");
define("BANLAN_30", "Aizlieguma ilgums");
define("BANLAN_31", "(Izmantojiet tukšu ziņojumu, ja vēlaties, lai lietotājs saņemtu tukšu ekrānu)");
define("BANLAN_32", "Nenoteikts");
define("BANLAN_34", "Beidzies");
define("BANLAN_35", "Imports/Eksports");
define("BANLAN_36", "Eksporta Tips");
define("BANLAN_37", "Lauka atdalītājs");
define("BANLAN_38", "Citāts (apaļo katru vērtību)");
define("BANLAN_39", "Eksports");
define("BANLAN_40", "Aizlieguma sarakts eksports");
define("BANLAN_41", "Aizlieguma saraksts importēt");
define("BANLAN_42", "Importēšanas IZvēles");
define("BANLAN_43", "Aizstāt visus esošos aizliegumus, kas tiek importēti");
define("BANLAN_44", "Izmantojiet derīguma termiņu/laiku no importa");
define("BANLAN_45", "Imports");
define("BANLAN_46", "Importēt Failu:");
define("BANLAN_47", "Faila ielādes kļūda");
define("BANLAN_48", "Dzēsts  [y] beidzies aizliegumu saraksta ieraksti");
define("BANLAN_49", "CSV importēšana: nesabalansētas kotācijas rindā");
define("BANLAN_50", "CSV importēšana: kļūda, rakstot banlist ierakstu rindā");
define("BANLAN_51", "CSV importēšana: veiksme, [y] līnijas, kas importētas no faila");
define("BANLAN_52", "Balts saraksts");
define("BANLAN_53", "Pievienot baltajam sarakstam");
define("BANLAN_54", "Nav ierakstu baltajā sarakstā");
define("BANLAN_55", "Ieraksta datums");
define("BANLAN_56", "IP / e-pasts, lietotājs");
define("BANLAN_57", "Lietotājs");
define("BANLAN_58", "Pievienojiet lietotājus baltajam sarakstam");
define("BANLAN_59", "Rediģēt esošo ierakstu baltajā sarakstā");
define("BANLAN_60", "Rediģēt esošo banlist ierakstu");
define("BANLAN_61", "Esošais ieraksts no balta saraksta");
define("BANLAN_63", "Izmantojiet reverso DNS, lai atļautu mītnes aizliegumu");
define("BANLAN_64", "Reversa DNS piekļuves, pievienojot aizliegumu");
define("BANLAN_65", "Ieslēdzot šo iespēju, jūs ļausiet lietotājiem aizliegt pēc resursdatora nosaukuma, nevis vienkārši IP vai e-pasta adreses. <br /> PIEZĪME: Tas var ietekmēt ielādes laiku dažos saimniekos vai ja serveris nereaģē");
define("BANLAN_66", "Ja notiek aizliegums, šī opcija pievieno aizliegto adresi domēnam");
define("BANLAN_67", "Iestatiet maksimālo piekļuves līmeni");
define("BANLAN_68", "Tas nosaka maksimālo piekļuves vietu skaitu 5 minūšu laikā");
define("BANLAN_69", "dalībniekiem");
define("BANLAN_70", "viesiem");
define("BANLAN_71", "Retrigger aizlieguma periods");
define("BANLAN_72", "Aizlieguma iespējas");
define("BANLAN_73", "Tas atsāks aizlieguma periodu, ja aizliegtais lietotājs piekļūst vietnei");
define("BANLAN_74", "Banlist uzturēšana");
define("BANLAN_75", "Noņemiet izbeigušos aizliegumus no saraksta");
define("BANLAN_76", "Izpildīt");
define("BANLAN_77", "Ziņojumi / Ban periodi");
define("BANLAN_78", "Rezultātu skaits ir pārsniegts ([x] pieprasījumi noteiktajā laikā)");
define("BANLAN_79", "CSV Eksporta formāts:");
define("BANLAN_80", "CSV importēšanas formāts:");
define("BANLAN_81", "Ban darbības žurnāls");
define("BANLAN_82", "Nav ierakstu Ban darbības žurnālā");
define("BANLAN_83", "Datums Laiks");
define("BANLAN_84", "IP Adrese");
define("BANLAN_85", "Papildus informācija");
define("BANLAN_86", "Ar aizliegumu saistīti pasākumi");
define("BANLAN_87", "Kopā [y] ieraksti sarakstā");
define("BANLAN_88", "Tukšs ban darbību žurnāls");
define("BANLAN_89", "Žurnāla fails ir dzēsts");
define("BANLAN_90", "Dzēšot log failu, radās kļūda");
define("BANLAN_91", "Datuma / laika formāts aizlieguma žurnālam");
define("BANLAN_92", "Skatīt strftime funkciju lapu pie php.net");
define("BANLAN_93", ".");
define("BANLAN_100", "Nezināms");
define("BANLAN_101", "Rokasgrāmata");
define("BANLAN_102", "Plūdi");
define("BANLAN_103", "Rezultātu skaits");
define("BANLAN_104", "Pieteikšanās kļūme");
define("BANLAN_105", "Importēts");
define("BANLAN_106", "Lietotājs");
define("BANLAN_107", "Nezināms");
define("BANLAN_108", "Nezināms");
define("BANLAN_109", "Vecs");
define("BANLAN_110", "Iespējams, ka aizliegums, kas tika noteikts pirms e107, tika paaugstināts no 0,7x");
define("BANLAN_111", "Ievadījis administrators");
define("BANLAN_112", "Mēģinājumi vietni atjaunināt pārāk ātri");
define("BANLAN_113", "Mēģinājumi piekļūt vietnei pārāk bieži no vienas un tās pašas adreses");
define("BANLAN_114", "Vairāki neveiksmīgi pieteikšanās mēģinājumi no tā paša lietotāja");
define("BANLAN_115", "Pievienots no ārējā saraksta");
define("BANLAN_116", "IP adrese ir aizliegta, ņemot vērā lietotāja aizliegumu");
define("BANLAN_117", "Rezervēts iemesls");
define("BANLAN_118", "Rezervēts iemesls");
define("BANLAN_119", "Norāda importa kļūdu - iepriekš importētie aizliegumi");
define("BANLAN_120", "Balta saraksta ieraksts");
define("BANLAN_121", "Melnā saraksta ieraksts");
define("BANLAN_122", "Melnais saraksts");
define("BANLAN_123", "Pievienot melnajam sarakstam");
define("BANLAN_124", "Beidzas");
define("BANLAN_125", "Izmantojiet manu IP");
define("BANLAN_126", "IP / e-pasts");
define("BANLAN_127", "Dzēst visus [x] neizdevās pieteikumvārdus no datu bāzes");
