<?php
/*
 * Copyright (C) 2008-2013 e107 Inc (e107.org), Licensed under GNU GPL (http://www.gnu.org/licenses/gpl.txt)
 *
 * Admin Language File
 *
*/
define("EPL_ADLAN_0", "Instalēt");
define("EPL_ADLAN_1", "Atinstalēt");
define("EPL_ADLAN_2", "Vai esat pārliecināts, ka vēlaties atinstalēt šo spraudni?");
define("EPL_ADLAN_3", "Apstiprināt atinstalēšanu");
define("EPL_ADLAN_4", "Atinstalēt anulēts");
define("EPL_ADLAN_5", "Instalēšanas procedūra radīs jaunas preferenču ierakstus.");
define("EPL_ADLAN_6", "... tad noklikšķiniet šeit, lai sāktu instalēšanas procedūru");
define("EPL_ADLAN_7", "Datubāzes tabulas veiksmīgi modernizētas.");
define("EPL_ADLAN_8", "Labi izveidotie preferenču iestatījumi");
define("EPL_ADLAN_9", "SQL komandas neizdevās. Pārbaudiet, vai visas jaunināšanas izmaiņas ir kārtībā.");
define("EPL_ADLAN_10", "Vārds");
define("EPL_ADLAN_11", "Versija");
define("EPL_ADLAN_13", "Savietojams");
define("EPL_ADLAN_14", "Apraksts");
define("EPL_ADLAN_15", "Lasīt README failu, lai iegūtu vairāk informācijas");
define("EPL_ADLAN_16", "Informācija par spraudni");
define("EPL_ADLAN_17", "Vairāk info ...");
define("EPL_ADLAN_18", "Neizdevās veiksmīgi izveidot šo spraudni tabulu (-s)");
define("EPL_ADLAN_19", "Datubāzes tabulas veiksmīgi izveidotas.");
define("EPL_ADLAN_21", "Spraudnis jau ir instalēts");
define("EPL_ADLAN_22", "Uzstādīts");
define("EPL_ADLAN_23", "Nav instalēts");
define("EPL_ADLAN_24", "Jaunināšana pieejams");
define("EPL_ADLAN_25", "Nav nepieciešamības instalēt");
define("EPL_ADLAN_26", "... tad noklikšķiniet šeit, lai sāktu atinstalēt procedūru");
define("EPL_ADLAN_27", "Nevaru veiksmīgi izdzēst");
define("EPL_ADLAN_28", "Datubāzes tabulas veiksmīgi izdzēstas");
define("EPL_ADLAN_29", "Priekšroka iestatījumi veiksmīgi izdzēsti");
define("EPL_ADLAN_30", "lūdzu, izdzēsiet to manuāli.");
define("EPL_ADLAN_31", "Lūdzu, izdzēsiet mapi tagad");
define("EPL_ADLAN_32", "un visi faili tajā iekšā, lai pabeigtu atinstalēšanas procesu.");
define("EPL_ADLAN_33", "Spraudnis ir veiksmīgi instalēts.");
define("EPL_ADLAN_34", "Plugin veiksmīgi atjaunināts.");
define("EPL_ADLAN_35", "Parser uzstādījumi veiksmīgi pievienoti.");
define("EPL_ADLAN_36", "Parser koda ievietošanas neizdevās, nepareizi formatēts.");
define("EPL_ADLAN_37", "Augšupielādēt spraudni (.zip formāts)");
define("EPL_ADLAN_38", "Augšupielādēt spraudni");
define("EPL_ADLAN_39", "Failu nevarēja augšupielādēt kā ".e_PLUGIN." mapei nav pareizu tiesību - lūdzu, mainiet rakstīšanas atļaujas un atkārtoti augšupielādējiet failu.");
define("EPL_ADLAN_40", "Admin paziņojums");
define("EPL_ADLAN_41", "Šis fails, šķiet, nav derīgs .zip vai .tar arhīvs.");
define("EPL_ADLAN_42", "Radās kļūda, nevarēs atkārtoti arhivēt failu");
define("EPL_ADLAN_43", "Jūsu spraudnis ir augšupielādēts un pievienots atinstalēto spraudņu sarakstam.");
define("EPL_ADLAN_44", "Automātiskā spraudņa augšupielāde un ekstrakcija ir atspējota, jo augšupielāde uz jūsu spraudņu mapi pašlaik nav atļauta - ja vēlaties to izdarīt, lūdzu, mainiet atļaujas mapē" .e_PLUGIN. ", lai atļautu augšupielādē.");
define("EPL_ADLAN_45", "Jūsu izvēlnes vienums ir augšupielādēts un izņemts, lai aktivizētu, dodieties uz <a href='".e_ADMIN."menus.php'> jūsu izvēlņu lapu </a>.");
define("EPL_ADLAN_46", "PCLZIP izvilkuma kļūda:");
define("EPL_ADLAN_47", "PCLTAR ekstrakcijas kļūda:");
define("EPL_ADLAN_48", "kods:");
define("EPL_ADLAN_49", "tabulas, kas nav dzēstas, veicot atinstalēšanas procesu pēc pieprasījuma");
define("EPL_WEBSITE", "Tīmekļa vietne");
define("EPL_NOINSTALL", "Nav nepieciešama instalēšana, vienkārši aktivizējiet savu izvēlņu ekrānu. Lai atinstalētu, izdzēsiet");
define("EPL_DIRECTORY", "mape.");
define("EPL_NOINSTALL_1", "Nav nepieciešams instalēt, lai noņemtu dzēšanu");
define("EPL_UPGRADE", "Atjaunot uz:");
define("EPL_ADLAN_50", "Komentāri veiksmīgi izdzēsti");
define("EPL_ADLAN_53", "Katalogs nav rakstāms");
define("EPL_ADLAN_54", "Lūdzu, izvēlieties spraudņa atinstalēšanas opcijas:");
define("EPL_ADLAN_55", "Atinstalēt spraudni");
define("EPL_ADLAN_57", "Dzēst spraudņu tabulas");
define("EPL_ADLAN_58", "Ja tabulas netiek noņemtas, spraudni var pārinstalēt bez datu zuduma. Tabulu izveide pārinstalēšanas laikā neizdevusies. Lai noņemtu tabulas, tās būs manuāli jāizdzēš.");
define("EPL_ADLAN_59", "Dzēst spraudņu failus");
define("EPL_ADLAN_60", "e107 mēģinās noņemt visus ar spraudni saistītos failus.");
define("EPL_ADLAN_62", "Atcelt atinstalēšanu");
define("EPL_ADLAN_63", "Atinstalēt:");
define("EPL_ADLAN_64", "mape");
define("EPL_ADLAN_70", "Nepieciešams spraudnis nav instalēts:");
define("EPL_ADLAN_71", "Nepieciešama jauna spraudņa versija:");
define("EPL_ADLAN_72", "Versija:");
define("EPL_ADLAN_73", "Nepieciešams PHP paplašinājums nav ielādēts:");
define("EPL_ADLAN_74", "Nepieciešama jaunāka PHP versija:");
define("EPL_ADLAN_75", "Nepieciešama jauna MySQL versija:");
define("EPL_ADLAN_76", "Kļūda plugin.xml");
define("EPL_ADLAN_77", "Nevar atrast spraudni.xml");
define("EPL_ADLAN_78", "Dzēst lietotāja klases, kas izveidotas ar spraudni:");
define("EPL_ADLAN_79", "Izdzēsiet tikai tos, ja tos neizmantojat citiem mērķiem.");
define("EPL_ADLAN_80", "Dzēst paplašinātus lietotāja laukus, kas izveidoti ar spraudni:");
define("EPL_ADLAN_81", "xhtml");
define("EPL_ADLAN_82", "ikona");
define("EPL_ADLAN_83", "Piezīmes");
define("EPL_ADLAN_84", "Instalēt atlasīto");
define("EPL_ADLAN_85", "Atinstalēt atlasītos");
define("EPL_ADLAN_86", "Visi faili noņemti no");
define("EPL_ADLAN_87", "Faila dzēšana neizdevās");
define("EPL_ADLAN_88", "Radīts priekš v2");
define("EPL_ADLAN_89", "Meklēt tiešsaistē");
define("EPL_ADLAN_90", "šobrīd ir nepieciešama cURL, lai izmantotu šo funkciju. Sazinieties ar savu tīmekļa mitināšanas pakalpojumu sniedzēju, lai iespējotu CURL");
define("EPL_ADLAN_91", "Nākotnes");
define("EPL_ADLAN_92", "Pirkt");
define("EPL_ADLAN_93", "Bezmaksas");
define("EPL_ADLAN_94", "Savienošana ...");
define("EPL_ADLAN_95", "Nevar turpināt");
define("EPL_ADLAN_96", "piem., http://website.com/some-plugin.zip");
define("EPL_ADLAN_97", "Radās problēma, ekstrahējot .zip failu savā spraudņu direktorijā.");
define("EPL_ADLAN_98", "Nezināms fails:");
define("EPL_ADLAN_99", "Kļūdu ziņojumi virs šīs līnijas");
define("EPL_ADLAN_100", "noklikšķiniet šeit, lai instalētu dažus");
define("EPL_ADLAN_101", "Nav instalēti spraudņi - [x].");
define("EPL_ADLAN_102", "Šis vednis izveidos jūsu spraudņa administratora zonu un ģenerēs plugin.xml meta failu. Pirms sākat:");
define("EPL_ADLAN_103", "Izveidot jaunu rakstāmu mapi katalogā [x], piemēram, [b] myplugin [/ b]");
define("EPL_ADLAN_105", "Izveidojiet tabulu, izmantojot phpMyAdmin tajā pašā datubāzē kā e107 un ar tādu pašu tabulas prefiksu, piemēram, [b] e107_myplugin [/b]");
define("EPL_ADLAN_106", "Izvēlieties spraudņa mapi, lai sāktu.");
define("EPL_ADLAN_107", "Izveidot administrācijas apgabalu un xml failu:");
define("EPL_ADLAN_108", "Pārbaudīt valodas failus:");
define("EPL_ADLAN_109", "Basic Info");
define("EPL_ADLAN_112", "Pārskatīt visus laukus un vajadzības gadījumā tos mainīt");
define("EPL_ADLAN_113", "Pārskatīt visas cilnes pirms noklikšķināšanas uz 'Izveidot'.");
define("EPL_ADLAN_114", "spraudnis Celtnieks");
define("EPL_ADLAN_115", "2. darbība");
define("EPL_ADLAN_116", "Teksta lodziņš");
define("EPL_ADLAN_117", "Teksta aile (numurs)");
define("EPL_ADLAN_118", "Teksta lodziņš (url)");
define("EPL_ADLAN_119", "Teksta apgabals");
define("EPL_ADLAN_120", "Bagātināta teksta apgabals");
define("EPL_ADLAN_121", "True / False");
define("EPL_ADLAN_122", "Pielāgota funkcija");
define("EPL_ADLAN_123", "attēls");
define("EPL_ADLAN_124", "Nomest lejā");
define("EPL_ADLAN_125", "DropDown (lietotāju klases)");
define("EPL_ADLAN_126", "DropDown (valodas)");
define("EPL_ADLAN_127", "ikona");
define("EPL_ADLAN_128", "Fails");
define("EPL_ADLAN_129", "Preferences nosaukums");
define("EPL_ADLAN_130", "noklusējuma vērtība");
define("EPL_ADLAN_131", "Lauka tips ...");
define("EPL_ADLAN_132", "[x] ir izveidots");
define("EPL_ADLAN_133", "[x] trūkst!");
define("EPL_ADLAN_134", "Lūdzu izveidojiet [b] [x] [/ b] jūsu spraudņu direktorijā ar šādu saturu: [y]");
define("EPL_ADLAN_135", "Jūsu spraudņa vārds (jāraksta angļu valodā)");
define("EPL_ADLAN_136", "Ja jums ir valodas fails, ievadiet spraudņa nosaukuma vērtību LAN_XXX");
define("EPL_ADLAN_137", "Jūsu spraudņa izveides datums");
define("EPL_ADLAN_138", "Jūsu spraudņa versija: formāts: x.x vai x.x.x");
define("EPL_ADLAN_139", "Savietojams ar šo e107 versiju");
define("EPL_ADLAN_140", "Autora vārds");
define("EPL_ADLAN_141", "Autora vietnes URL");
define("EPL_ADLAN_142", "Spraudņa īsa viena rindiņa apraksts");
define("EPL_ADLAN_143", "(Jābūt rakstītiem angļu valodā)");
define("EPL_ADLAN_144", "Atslēgvārds / tags šim spraudim");
define("EPL_ADLAN_145", "Spraudņa pilns apraksts");
define("EPL_ADLAN_146", "Kāda ir šī spraudņa kategorija?");
define("EPL_ADLAN_147", "iestatījumi");
define("EPL_ADLAN_148", "lietotāji");
define("EPL_ADLAN_149", "saturs");
define("EPL_ADLAN_150", "rīki");
define("EPL_ADLAN_151", "pārvaldīt");
define("EPL_ADLAN_152", "dažādi");
define("EPL_ADLAN_153", "izvēlne");
define("EPL_ADLAN_154", "par");
define("EPL_ADLAN_155", "Saglabāts:");
define("EPL_ADLAN_156", "Nevarēja saglabāt:");
define("EPL_ADLAN_157", "Galvenā apgabala");
define("EPL_ADLAN_158", "Kategorijas");
define("EPL_ADLAN_159", "Cits 1");
define("EPL_ADLAN_160", "Cits 2");
define("EPL_ADLAN_161", "Cits 3");
define("EPL_ADLAN_162", "Cits 4");
define("EPL_ADLAN_163", "Izslēgt šo tabulu");
define("EPL_ADLAN_164", "lauks");
define("EPL_ADLAN_165", "paraksts");
define("EPL_ADLAN_166", "Tips");
define("EPL_ADLAN_167", "Dati");
define("EPL_ADLAN_168", "Platums");
define("EPL_ADLAN_169", "Partija");
define("EPL_ADLAN_170", "filtrs");
define("EPL_ADLAN_171", "Iekšlīnija");
define("EPL_ADLAN_172", "Apstiprināt");
define("EPL_ADLAN_173", "Displejs");
define("EPL_ADLAN_174", "Palīdzības padomi");
define("EPL_ADLAN_175", "Lasīt parms");
define("EPL_ADLAN_176", "Rakstīt parms");
define("EPL_ADLAN_177", "Lauks jāaizpilda");
define("EPL_ADLAN_178", "Parādīts pēc noklusējuma");
define("EPL_ADLAN_179", "Teksta lodziņš");
define("EPL_ADLAN_180", "Slēpts");
define("EPL_ADLAN_181", "True / False");
define("EPL_ADLAN_182", "Teksta lauka (numurs)");
define("EPL_ADLAN_183", "Nolaizamais");
define("EPL_ADLAN_184", "Nolaižamais (lietotāju klases)");
define("EPL_ADLAN_186", "Pielāgota funkcija");
define("EPL_ADLAN_187", "Slēpts");
define("EPL_ADLAN_188", "Lietotājs");
define("EPL_ADLAN_189", "Teksta lodziņš");
define("EPL_ADLAN_190", "Nolaižamais");
define("EPL_ADLAN_191", "Pielāgota funkcija");
define("EPL_ADLAN_192", "Slēpts");
define("EPL_ADLAN_193", "Teksta lodziņš");
define("EPL_ADLAN_194", "Teksta lodziņš (url)");
define("EPL_ADLAN_195", "Teksta laukums (e-pasts)");
define("EPL_ADLAN_196", "Teksta aile (ip)");
define("EPL_ADLAN_197", "Teksta laukums (numurs)");
define("EPL_ADLAN_198", "Teksta laukums (parole)");
define("EPL_ADLAN_199", "Teksta laukums (atslēgvārdi)");
define("EPL_ADLAN_200", "Nolaižamais");
define("EPL_ADLAN_201", "Nolaižamais (lietotāju klases)");
define("EPL_ADLAN_202", "Nolaižamais (valodas)");
define("EPL_ADLAN_203", "ikona");
define("EPL_ADLAN_204", "attēls");
define("EPL_ADLAN_205", "Fails");
define("EPL_ADLAN_206", "Pielāgota funkcija");
define("EPL_ADLAN_207", "Slēpts");
define("EPL_ADLAN_208", "Teksta apgabals");
define("EPL_ADLAN_209", "bagātinātā teksta apgabals");
define("EPL_ADLAN_210", "Teksta lodziņš");
define("EPL_ADLAN_211", "Teksta laukums (atslēgvārdi)");
define("EPL_ADLAN_212", "Pielāgota funkcija");
define("EPL_ADLAN_213", "Attēls (virkne)");
define("EPL_ADLAN_214", "Attēli (masīvs)");
define("EPL_ADLAN_215", "Slēpts");
define("EPL_ADLAN_216", "Uzklikšķināt šeit");
define("EPL_ADLAN_217", "[x], lai aktivizētu jūsu ģenerēto administratīvo zonu");
define("EPL_ADLAN_218", "Nevarēja rakstīt uz [x]");
define("EPL_ADLAN_219", "Nav izveidoti faili. Lūdzu, kopējiet & amp; ielīmējiet zemāk esošo kodu savos failos.");
define("EPL_ADLAN_220", "Atrodiet spraudņus");
define("EPL_ADLAN_221", "valodas failu pārbaude");
define("EPL_ADLAN_222", "Spraudņu Faili");
define("EPL_ADLAN_223", "Lietots");
define("EPL_ADLAN_224", "neizmantots");
define("EPL_ADLAN_225", "Negaidīts");
define("EPL_ADLAN_226", "Spraudņu valodas failu pārbaude");
define("EPL_ADLAN_227", "Pārskats par izmaiņām");
define("EPL_ADLAN_228", "Plugin mapes tiek skenētas ik pēc [x] minūtēm, lai veiktu izmaiņas. Noklikšķiniet uz zemāk redzamās pogas, lai skenētu tagad.");
define("EPL_ADLAN_229", "Atsvaidzināt");
define("EPL_ADLAN_230", "Lejupielāde un instalēšana:");
define("EPL_ADLAN_231", "Noņemt ikonas no Media-Manager");
define("EPL_ADLAN_232", "Izveidot failus");
define("TPVLAN_81", "Lejupielāde ...");
define("TPVLAN_82", "Lejupielādēt pabeigta!");
define("EPL_ADLAN_233", "Pievienojot saiti:");
define("EPL_ADLAN_234", "Noņemošā saite:");
define("EPL_ADLAN_235", "Automātiskā lejupielāde nav iespējama");
define("EPL_ADLAN_236", "Lūdzu, ielādēt manuāli");
define("EPL_ADLAN_237", "Lejupielāde");
define("EPL_ADLAN_238", "Instalācija pabeigta!");
define("EPL_ADLAN_239", "Pievienojot tabulu:");
define("EPL_ADLAN_240", "tabulas noņemšana:");
define("EPL_ADLAN_241", "pievienošana Pref:");
define("EPL_ADLAN_242", "Pref: noņemšana");
define("EPL_ADLAN_243", "Pref: atjaunināšana");
define("EPL_ADLAN_244", "Instalēšanas laikā ir atļautas tikai 5 multivides kategorijas");
define("EPL_ADLAN_245", "Media Media pievienošana: [x]");
define("EPL_ADLAN_246", "Visu mediju kategoriju dzēšana, kuras pieder: [x]");
define("EPL_ADLAN_247", "Instalējamie atjauninājumi");
define("EPL_ADLAN_249", "Paplašinātā lauka pievienošana:");
define("EPL_ADLAN_250", "Izvērstā lauka noņemšana:");
define("EPL_ADLAN_251", "Extended field paliek vietā:");
define("EPL_ADLAN_252", "Perms:");
define("EPL_ADLAN_253", "Pabeigts");
define("LAN_RELEASED", "Atbrīvots");
define("LAN_REPAIR_PLUGIN_SETTINGS", "Remonta spraudņu iestatījumi");
define("LAN_SYNC_WITH_GIT_REPO", "Sinhronizēt ar Git Repo");
define("LAN_ADDONS", "paplašinājumi");
define("LAN_UPGRADE_SUCCESSFUL", "Jaunināšana veiksmīga");
define("LAN_INSTALL_SUCCESSFUL", "instalēšana veiksmīga");
define("LAN_INSTALL_FAIL", "Instalācija neizdevās!");
define("LAN_UNINSTALL_FAIL", "Nevar atinstalēt!");
define("LAN_PLUGIN_IS_USED", "[x] spraudni izmanto:");
define("EPL_ADLAN_254", "Tas pārbaudīs jūsu spraudņa valodas failus, lai iegūtu kļūdas un parastos vai dublētus LAN definīcijas.");
define("EPL_ADLAN_255", "Failu pārrakstīšana");
define("EPL_ADLAN_256", "Izlaista [x] (jau eksistē)");
