<?php
/*
 * e107 website system
 *
 * Copyright (C) 2008-2017 e107 Inc (e107.org)
 * Released under the terms and conditions of the
 * GNU General Public License (http://www.gnu.org/licenses/gpl.txt)
 *
 * Language file - user admin
 *
 *
*/
define("USRLAN_1", "Saglabātie opcijas");
define("USRLAN_3", "tagad uzskaitīti administrators - lai iestatītu atļaujas, lūdzu, dodieties uz");
define("USRLAN_4", "Administratora lapa");
define("USRLAN_5", "Jūs nevarat noņemt administratora galvenā administratora statusu");
define("USRLAN_6", "ir noticis administratora statuss");
define("USRLAN_7", "Jūs nevarat aizliegt galvenā vietnes administratoru");
define("USRLAN_8", "Lietotājs aizliegts.");
define("USRLAN_9", "Lietotājs nav aizliegts");
define("USRLAN_10", "Lietotājs izdzēsts");
define("USRLAN_11", "Dzēst anulēto.");
define("USRLAN_12", "Jūs nevarat izdzēst galvenās vietnes administratoru.");
define("USRLAN_13", "Lūdzu, apstipriniet, ka vēlaties dzēst šo dalībnieku");
define("USRLAN_16", "Apstiprināt dzēšanu");
define("USRLAN_17", "Apstiprināt dzēst lietotāju");
define("USRLAN_30", "aizliegums");
define("USRLAN_32", "Aktivizēt");
define("USRLAN_33", "Atbloķēt");
define("USRLAN_34", "Noņemt admin statusu");
define("USRLAN_35", "Padarīt admin");
define("USRLAN_36", "Iestatīt klasi");
define("USRLAN_44", "Atļaut dalībniekiem augšupielādēt iemiesojumu?");
define("USRLAN_47", "maksimālais avatar platums (pikseļos)");
define("USRLAN_48", "noklusējums ir 120");
define("USRLAN_49", "maksimālais avatar augstums (pikseļos)");
define("USRLAN_50", "noklusējums ir 100");
define("USRLAN_51", "Atjaunināšanas opcijas");
define("USRLAN_52", "Dalībnieku opcijas");
define("USRLAN_53", "Ļaujiet dalībniekiem augšupielādēt fotogrāfiju?");
define("USRLAN_54", "Noklikšķiniet šeit, lai izdzēstu visus inaktivētos lietotājus");
define("USRLAN_55", "Apgriezt");
define("USRLAN_56", "Svītrots");
define("USRLAN_57", "Dzēst neaktivētos dalībniekus ...");
define("USRLAN_58", "faila augšupielāde ir atspējota php.ini");
define("USRLAN_59", "Ātrās pievienošanas lietotājs");
define("USRLAN_60", "Pievienot lietotāju");
define("USRLAN_61", "Displeja vārds");
define("USRLAN_63", "Atkārtoti ievadiet paroli");
define("USRLAN_64", "e-pasta adrese");
define("USRLAN_65", "Šo parādāmo vārdu nevar uzskatīt par derīgu, lūdzu, izvēlieties citu parādāmo vārdu");
define("USRLAN_66", "Šis parādītais nosaukums jau pastāv datu bāzē, lūdzu, izvēlieties citu parādāmo vārdu");
define("USRLAN_67", "Šīs divas paroles neatbilst");
define("USRLAN_68", "Jūs atstājāt neaizpildītos laukus (-us)");
define("USRLAN_69", "Tas, šķiet, nav derīga e-pasta adrese");
define("USRLAN_78", "Lietotāja vārds");
define("USRLAN_79", "statuss");
define("USRLAN_80", "Informācija");
define("USRLAN_84", "Ir");
define("USRLAN_85", "lietotāji, kuri nav aktivizējuši savu kontu - tālāk noklikšķiniet, lai dzēstu.");
define("USRLAN_86", "Lietotājs verificēts");
define("USRLAN_87", "Lietotāja iestatījumi atjaunināti");
define("USRLAN_88", "Lietotāja klases atjaunināts");
define("USRLAN_90", "meklēšana / atsvaidzināt");
define("USRLAN_91", "Klase");
define("USRLAN_92", "Nepareizas rakstzīmes lietotājvārdā");
define("USRLAN_93", "Dzēst nepārbaudītus lietotājus");
define("USRLAN_94", "Dzēst pierakstīšanos, ja tā nav apstiprināta pēc šī laika - atstāt tukšu, lai neizmantotu šo iespēju <br /> Šī opcija tiek ignorēta, ja lietotāja pierakstīšanās ir admin moderēta");
define("USRLAN_95", "minūtes");
define("USRLAN_112", "Pārstādīt e-pastu");
define("USRLAN_113", "Reģistrācijas informācija par");
define("USRLAN_114", "Cienījamie");
define("USRLAN_115", "paldies par jūsu reģistrāciju.");
define("USRLAN_116", "Lūdzu, apstipriniet, ka vēlaties nosūtīt apstiprinājuma e-pastu uz:");
define("USRLAN_117", "Noklikšķiniet uz zemāk redzamās pogas, lai pārbaudītu šādu e-pastu:");
define("USRLAN_118", "Testa e-pasts");
define("USRLAN_119", "Tests [x]");
define("USRLAN_120", "Iestatīt nodarbības");
define("USRLAN_121", "Pasta sūtīšana");
define("USRLAN_122", "Laipni lūdzam");
define("USRLAN_123", "Jūsu reģistrācija ir saņemta un izveidota.");
define("USRLAN_124", "Pašlaik jūsu konts tiek atzīmēts kā neaktīvs, lai aktivizētu savu kontu, lūdzu, pārejiet uz šo saiti");
define("USRLAN_125", "No");
define("USRLAN_126", "Ļauj lietotājiem novērtēt lietotājus");
define("USRLAN_127", "Atļaut komentārus lietotāja profilā");
define("USRLAN_128", "Lietotājvārds (login name)");
define("USRLAN_129", "reāls nosaukums");
define("USRLAN_130", "Iespējot tiešsaistes lietotāju izsekošanu");
define("USRLAN_131", "Jums jāaktivizē šī opcija, lai izmantotu tiešsaistes lietotāju izsekošanas iespējas, piemēram, online.php, foruma tiešsaistes informāciju un tiešsaistes izvēlnes");
define("USRLAN_132", "Iespējot");
define("USRLAN_133", "Piespiediet lietotājus, lai atjauninātu iestatījumus");
define("USRLAN_134", "Iespējojot šo opciju, lietotājs automātiski nosūta lietotāja iestatījumus, ja nepareizs lietotāja lauks");
define("USRLAN_135", "Nevienā IP adresē nav lietotāja informācijas, IP nav aizliegts");
define("USRLAN_136", "Vairāki lietotāji, kas atrasti ar IP adresi {IP}; IP nav aizliegts.");
define("USRLAN_137", "Lietotāja IP adreses {IP} aizliegta.");
define("USRLAN_138", "Nepārbaudīti lietotāji");
define("USRLAN_139", "Jūsu konts ir aktivizēts. \ n \ nJūs varat apmeklēt {SITEURL} un piesakieties vietnē, izmantojot jūsu ievadīto pieteikšanās informāciju.");
define("USRLAN_140", "Aktivizēšanas e-pasts vēlreiz nosūtīts uz");
define("USRLAN_141", "Neizdevās atkārtoti sūtīt aktivizācijas e-pastu uz");
define("USRLAN_142", "ar šādu aktivizācijas saiti");
define("USRLAN_143", "Pārbaudīt bounces");
define("USRLAN_144", "Atkārtoti nosūtīt apstiprinājuma e-pastu visiem");
define("USRLAN_145", "Atgriezušies lietotāji");
define("USRLAN_146", "Informācija par dalībnieku ir pieejama");
define("USRLAN_147", "E-pasta adresi jau izmanto aizliegtais lietotājs");
define("USRLAN_148", "E-pasta adrese ir aizliegta");
define("USRLAN_149", "Dzēst atzīmētos e-pasta ziņojumus");
define("USRLAN_150", "Dzēst visus e-pasta ziņojumus");
define("USRLAN_151", "Notīrīt atlēcienus, pieprasīt aktivizēšanu");
define("USRLAN_152", "Notīrīt lielību un aktivizēt");
define("USRLAN_153", "Dzēst neatspēks e-pastus");
define("USRLAN_154", "Notīrīt e-pastu pārbaudītam");
define("USRLAN_155", "Total [w] e-pastus atrasts. [x] svītrots, izmantojot opcijas. [br] [y] lietotāji atzīmēti kā" atlekšanas "(ārpus [z] e-pasta adreses)");
define("USRLAN_156", "E-pasta adrese jau ir lietota");
define("USRLAN_161", "User ID [x] nosaukums [y] aizliegts");
define("USRLAN_162", "User ID [x] nosaukums [y] unbanned");
define("USRLAN_164", "Lietotāja ID [x] nosaukums [y] ((z]) veikts admin");
define("USRLAN_165", "Lietotāja ID [x] nosaukums [y] admin statuss atsaukts");
define("USRLAN_166", "Lietotāja ID [x] nosaukums [y] apstiprināts");
define("USRLAN_167", "Apstiprinājuma e-pasta ID [x] atsaukts uz [y] pie [z]");
define("USRLAN_169", "Kopā [x] atgriezušies e-pasta ziņojumi ir izdzēsti");
define("USRLAN_170", "Nejaušs lietotājvārds");
define("USRLAN_171", "Nejauša parole");
define("USRLAN_172", "Lietotāja konts ir izveidots ar sekojošo:");
define("USRLAN_179", "Lietotājs aizliegts:");
define("USRLAN_180", "IP adrese ({IP}) parādās baltajā sarakstā; IP nav aizliegts.");
define("USRLAN_181", "Izvēlēties lietotāja statusu un nosūtīt apstiprinājuma e-pastu lietotājam");
define("USRLAN_182", "Nepareizas rakstzīmes pieteikšanās vārds");
define("USRLAN_183", "Šis lietotājvārds jau tiek izmantots");
define("USRLAN_184", "Lietotāja vārda ilgums ārpus ierobežojumiem");
define("USRLAN_185", "Lietotāja konts ir izveidots jums vietnē {SITEURL} ar šādu pieteikšanos: <br /> <br /> <b> Lietotājvārds: </ b> {LOGINNAME} <br /> < b> Parole: </ b> {PASSWORD} <br/> <b> Aktivizēšanas saite: </ b> {ACTIVATION_LINK} <br /> <br />");
define("USRLAN_186", "Lūdzu, dodieties uz vietni, cik ātri vien iespējams, un piesakieties, pēc tam mainiet savu paroli, izmantojot opciju \" Iestatījumi \ . <br /> <br /> Jūs varat mainīt citus iestatījumus tajā pašā laiku. <br /> <br /> Ņemiet vērā, ka, ja tu to pazaudēsi, paroli nevarēs atgūt.");
define("USRLAN_187", "Piekļuve vietnei:");
define("USRLAN_188", "E-pasts nosūtīts veiksmīgi");
define("USRLAN_189", "Kļūda sūtot e-pastu");
define("USRLAN_190", "Jauns lietotāju pārbaudes laiks (dienas)");
define("USRLAN_191", "Administrators dažos apgabalos var noteikt ierobežojumus šajā periodā");
define("USRLAN_192", ".");
define("USRLAN_193", "Nekas nav mainīts - nav saglabāts");
define("USRLAN_194", "Parakstu var mainīt ar");
define("USRLAN_195", "pēdējais ziņojums");
define("USRLAN_198", "lauka nosaukums");
define("USRLAN_199", "Operācija");
define("USRLAN_200", "Vērtība");
define("USRLAN_201", "komentāru skaits");
define("USRLAN_202", "Vietņu apmeklējumu skaits");
define("USRLAN_203", "dalībnieku dienu skaits");
define("USRLAN_204", "Kodols");
define("USRLAN_206", "pašreizējais aprēķins");
define("USRLAN_207", "tips");
define("USRLAN_208", "Ranka Nosaukums");
define("USRLAN_209", "apakšējā robeža");
define("USRLAN_210", "Lang prefikss");
define("USRLAN_211", "Ranka Bilde");
define("USRLAN_212", "Lietotāja rangs");
define("USRLAN_214", "Pievienot jaunu rangu");
define("USRLAN_216", "- select image--");
define("USRLAN_219", "Vecāki par 30 dienām");
define("LAN_MAINADMIN", "Galvenais Admins");
define("LAN_NOTVERIFIED", "Nepārbaudīts");
define("LAN_BANNED", "Aizliegts");
define("LAN_BOUNCED", "Atlekošais");
define("LAN_UI_1_HOUR", "1 stunda");
define("LAN_UI_3_HOURS", "3 stundas");
define("LAN_UI_6_HOURS", "6 stundas");
define("LAN_UI_12_HOURS", "12 stundas");
define("LAN_UI_24_HOURS", "24 stundas");
define("LAN_UI_48_HOURS", "48 stundas");
define("LAN_UI_3_DAYS", "3 dienas");
define("USRLAN_220", "Visas userclasses");
define("USRLAN_221", "Rediģēt admin perms");
define("USRLAN_222", "Jūs gatavojaties izdzēst [x] ([y]) ar ID # [z]. Vai esat pārliecināts?");
define("USRLAN_223", "Lietotājs nav atrasts");
define("USRLAN_224", "E-pasts nosūtīts uz:");
define("USRLAN_225", "Neizdevās nosūtīt e-pastu uz:");
define("USRLAN_226", "Jums nav pietiekamu atļauju to izdarīt.");
define("USRLAN_227", "Nezināma kļūda: darbība neizdevās");
define("USRLAN_228", "Jūs gatavojaties lietot Lietotāju # [b] [x] [/ b]: [b] [y] [/ b] ([z]) [b] administrators [/ b].");
define("USRLAN_229", "Iestatīt atļaujas un noklikšķiniet uz [b] Update [/ b], lai turpinātu, vai [b] Atpakaļ [/ b], lai pārtrauktu.");
define("USRLAN_230", "Atjaunināt administratoru [x] ([y])");
define("USRLAN_231", "Nepietiekamas atļaujas, darbība pārtraukta.");
define("USRLAN_232", "trūkst aktivizācijas atslēgas.");
define("USRLAN_233", "Derīgs");
define("USRLAN_234", "Nederīgs");
define("USRLAN_235", "Lietotājam tagad ir jāpārbauda");
define("USRLAN_236", "darbība neizdevās.");
define("USRLAN_237", "Lietotājvārds un redzamais vārds nevar būt citāds (pamatojoties uz vietnes konfigurāciju). Displeja nosaukums ir iestatīts uz [b] [x] [/ b].");
define("USRLAN_238", "Jūsu pašreizējais statuss ir [b] Aktīvs [/ b]");
define("USRLAN_239", "Paziņojums un lietotāja statuss");
define("USRLAN_240", "Aktivizēt, nepaziņot");
define("USRLAN_241", "Aktivizēt, paziņot (parole)");
define("USRLAN_242", "Pieprasīt aktivizēšanu, paziņot (parole un aktivizēšanas saite)");
define("USRLAN_243", "Iestatīt atļaujas");
define("USRLAN_244", "Drošības pārkāpums (nepietiekamas atļaujas) - administrators [x] ([y], [z]) mēģināja noņemt [admin] statusu no [u] ([v], [w])");
define("USRLAN_245", "Drošības pārkāpums (nepietiekamas atļaujas) - administrators [x] ([y], [z]) mēģināja izveidot [u] ([v], [w]) sistēmas admin");
define("USRLAN_246", "(Nepieciešams)");
define("USRLAN_247", "Us.");
define("USRLAN_248", "Us.");
define("USRLAN_249", "Us.");
define("USRLAN_250", "Us.");
define("USRLAN_251", "Atstāt tukšu bez izmaiņām");
define("USRLAN_252", "Atkārtoti nosūtīt konta aktivizācijas e-pastu neaktivētiem lietotājiem");
define("USRLAN_253", "Vecāki par");
define("USRLAN_254", "Atjaunot visas paroles");
define("USRLAN_255", "Paziņot lietotāju");
define("USRLAN_256", "Cienījamie");
define("UCSLAN_1", "Paziņojuma e-pasta ziņojumu nosūtīšana uz");
define("UCSLAN_2", "Atjauninātās privilēģijas");
define("UCSLAN_4", "Jūsu privilēģijas ir atjauninātas");
define("UCSLAN_5", "Jums tagad ir piekļuve šādai (-ām) vietai (-ēm)");
define("UCSLAN_6", "Iestatīt lietotāju klasi");
define("UCSLAN_7", "Iestatīt nodarbības");
define("UCSLAN_9", "Klases atjaunotas.");
define("UCSLAN_10", "Apsveicam,");
define("UCSLAN_11", "Klases dalībnieka lietotāja ID [x] mainīts uz [y]");
define("UCSLAN_12", "Tikai dalībnieka privilēģijas");
define("USFLAN_1", "Nevar atrast plakāta IP adresi - informācija nav pieejama");
define("USFLAN_3", "Ziņojumi publicēti no IP adreses");
define("USFLAN_4", "Hosts");
define("USFLAN_5", "Noklikšķiniet šeit, lai pārsūtītu IP adresi administratora aizlieguma lapai");
define("USFLAN_6", "Lietotāja ID");
define("USFLAN_7", "Lietotāja informācija");
define("USRLAN_AS_1", "Pieteikties kā [x]");
define("USRLAN_AS_2", "Iziet no [x] konta");
define("USRLAN_AS_3", "Jūs jau esat pieteicies kā cita lietotāja konts. Lūdzu, izejiet no sākuma.");
