<?php
/*
 * e107 website system
 *
 * Copyright (C) 2008-2017 e107 Inc (e107.org)
 * Released under the terms and conditions of the
 * GNU General Public License (http://www.gnu.org/licenses/gpl.txt)
 *
 * Admin Language File
 *
*/
define("ADLAN_0", "Ziņas");
define("ADLAN_1", "Pārvaldīt ziņu priekšmetus");
define("ADLAN_2", "Izveidot ziņu vienumu");
define("ADLAN_3", "Jaunumu ziņu saraksts");
define("ADLAN_3a", "Ziņu iestatījumi");
define("ADLAN_5", "Rediģējiet vietnes preferences");
define("ADLAN_6", "Izvēlņu pārvaldnieks");
define("ADLAN_7", "Mainiet savu izvēlņu secību");
define("ADLAN_8", "Administratori");
define("ADLAN_9", "Pievienot/dzēst vietņu administratorus");
define("ADLAN_10", "Administratora parole");
define("ADLAN_11", "Nomainiet paroli");
define("ADLAN_12", "Doks");
define("ADLAN_13", "Sistēmas dokumentācija");
define("ADLAN_25", "Pārvaldiet lejupielādes");
define("ADLAN_28", "Sveiciena ziņa");
define("ADLAN_29", "Iestatiet statisku sveiciena ziņojumu");
define("ADLAN_30", "Failu menedžeris");
define("ADLAN_31", "Pārvaldīt/augšupielādēt failus");
define("ADLAN_34", "Bloķētais saraksts");
define("ADLAN_35", "Aizliegt apmeklētājus");
define("ADLAN_36", "Lietotāji");
define("ADLAN_37", "Pārraudzīt vietnes dalībniekus");
define("ADLAN_38", "Lietotāju klases");
define("ADLAN_39", "Izveidot/labot lietotāju klases");
define("ADLAN_40", "Apkope");
define("ADLAN_41", "Izņemiet vietni, lai veiktu apkopi");
define("ADLAN_42", "Lapas/Izvēlnes");
define("ADLAN_43", "Izveidojiet izvēlnes vienumus");
define("ADLAN_44", "Datu bāze");
define("ADLAN_45", "Datu bāzses pakalpojumi");
define("ADLAN_47", "Laipni lūdzam");
define("ADLAN_48", "Pieteicies");
define("ADLAN_49", "galvenais vietnes administrators");
define("ADLAN_51", "Lūdzu, piesakieties, lai piekļūtu administrācijas vietai");
define("ADLAN_52", "Admina Sākumlapa");
define("ADLAN_53", "Iziet no Admina lapas");
define("ADLAN_58", "Emocijas");
define("ADLAN_59", "Konfigurēt Emocijas");
define("ADLAN_60", "Sākumlapa");
define("ADLAN_61", "Konfigurējiet sākumlapas saturu");
define("ADLAN_66", "Meta Tagi");
define("ADLAN_67", "Pievienot/labot meta tagus");
define("ADLAN_68", "PHP Informācija");
define("ADLAN_69", "PHP Info lapa");
define("ADLAN_72", "Publiskās augšupielādes");
define("ADLAN_73", "Konfigurēt publisko failu augšupielādes");
define("ADLAN_74", "Kešatmiņa");
define("ADLAN_75", "Iestatīt kešatmiņas statusu");
define("ADLAN_78", "Paplašinātās lietotāju lauki");
define("ADLAN_79", "Labot paplašinātus lietotāja laukus");
define("ADLAN_86", "Aizliegts");
define("ADLAN_87", "Pieeja noliegta!");
define("ADLAN_89", "Administratora vārds");
define("ADLAN_90", "Administratora parole");
define("ADLAN_91", "Pieslēgties");
define("ADLAN_92", "Lūdzu, piesakieties, lai turpinātu administrāciju ...");
define("ADLAN_93", "Rādīt administratora funkcijas");
define("ADLAN_95", "Spraudņu Vadība");
define("ADLAN_98", "Spraudņu pārvaldnieks");
define("ADLAN_99", "Noklikšķiniet šeit, lai uzstādītu, uzturētu un konfigurētu spraudņus, kas nodrošina papildu funkcijas jūsu vietnē.");
define("ADLAN_102", "Kopš galvenās administratora paroles maiņas ir pagājušas vairāk nekā 30 dienas -");
define("ADLAN_103", "Noklikšķiniet šeit, lai to tagad mainītu");
define("ADLAN_104", "Drošība");
define("ADLAN_105", "Attēli");
define("ADLAN_106", "Attēla iestatījumi");
define("ADLAN_110", "Reģistrētie dalībnieki");
define("ADLAN_111", "Nepārbaudītie dalībnieki");
define("ADLAN_112", "Aizliegti lietotāji");
define("ADLAN_116", "Admina Žurnāls ...");
define("ADLAN_117", "Parādīt visus ierakstus");
define("ADLAN_118", "Notīrīt žurnālu");
define("ADLAN_119", "Nēpārbaudītas iesniegtās saites");
define("ADLAN_120", "Pieejams datubāzes atjauninājums, lūdzu, noklikšķiniet uz pogas, lai uzstādītu ...");
define("ADLAN_121", "Uzstādīt");
define("ADLAN_122", "Jauns atjauninājums ir gatavs uzstādīšanai! Noklikšķiniet, lai atarhivētu un uzstādītu v [x]");
define("ADLAN_132", "Valoda");
define("ADLAN_133", "noklusējums");
define("ADLAN_135", "Admin žurnāls");
define("ADLAN_136", "E-pasts");
define("ADLAN_137", "E-pasta iestatījumi un Izejošais pasts");
define("ADLAN_138", "Vietnes saites");
define("ADLAN_139", "Pievienot/labot/dzēst saites");
define("ADLAN_140", "Motīvu pārvaldnieks");
define("ADLAN_141", "Noklikšķiniet šeit, lai uzstādītu un konfigurētu motīvus, kas kontrolē jūsu vietnes izskatu.");
define("ADLAN_143", "Meklēšanas konfigurācija");
define("ADLAN_144", "Jūs esat vienkāršā skatīšanas režīmā, lai pārslēgtos uz uzlaboto skatu");
define("ADLAN_145", "noklikšķiniet šeit");
define("ADLAN_146", "Nesekmīgas pieteikšanās");
define("ADLAN_147", "Faila inspektors");
define("ADLAN_148", "Skenēt vietnes failus");
define("ADLAN_149", "Paziņot");
define("ADLAN_150", "Admina e-pasta paziņojumi");
define("ADLAN_151", "Galvenā");
define("ADLAN_153", "Admina Zona");
define("ADLAN_154", "Kļūda, sazinoties ar Sourceforge, lai pārbaudītu jauno versiju");
define("ADLAN_155", "Sistēmas žurnāli");
define("ADLAN_156", "Admin žurnāls, lietotāja audits, ritošā žurnāls");
define("ADLAN_157", "Uzdevumu grafiks");
define("ADLAN_158", "Cron Darbs un automatizēta apkope");
define("ADLAN_159", "URL konfigurācija");
define("ADLAN_160", "Konfigurēt vietnes vietrāžus URL");
define("ADLAN_161", "Pielāgotie lauki?");
define("ADLAN_162", "Ir pieejama jauna jūsu vietnes motīva versija:");
define("ADLAN_163", "Ir pieejama jauna uzstādītā spraudņa versija:");
define("ADLAN_164", "Veiksmīgi pievienojās kā [x].");
define("ADLAN_165", "Vietni darbina e107 sistēma");
define("ADLAN_166", "Atgriezties tīmekļa vietnē");
define("ADLAN_167", "Gaida Mailshots");
define("ADLAN_168", "Apmeklētāji");
define("ADLAN_169", "Unikālie apmeklētāji");
define("ADLAN_170", "Šī statistika ir paredzēts tikai demonstrācijas nolūkiem.");
define("ADLAN_171", "Uzstādiet vietnes statistikas spraudni");
define("ADLAN_185", "Pārslēgt sānu joslu");
define("ADLAN_186", "No jūsu sistēmas var droši izdzēst sekojošus vecos failus:");
define("ADLAN_187", "Nevar izveidot [x]. Lūdzu, pārbaudiet savas mapes atļaujas.");
define("ADLAN_188", "Jūsu laika zonas iestatījums [x] nav derīgs. Tas ir atiestatīts uz UTC. Lai mainītu, lūdzu, dodieties uz Admin -> Preferences -> Datuma attēlošanas opcijas.");
define("ADLAN_189", "Tālāk norādītie spraudņi nav savietojami ar šo e107 versiju un tie ir jāatinstalē:");
define("ADLAN_190", "Vajadzīga palīdzība?");
define("ADLAN_191", "Sazinieties ar mūsu kopienu par [bezmaksas atbalstu] ar jebkādiem jaunināšanas jautājumiem, ar kuriem jūs varat saskarties.");
define("ADLAN_192", "Sazinieties ar mūsu kopienu par [bezmaksas atbalstu] ar jebkādiem e107 jautājumiem, ar kuriem jūs varat saskarties.");
define("ADLAN_193", "Mape [x] nav rakstāma. Pirms turpiniet, lūdzu, izlabojiet.");
define("ADLAN_194", "Noteikta mantojuma avataru mape. Lūdzu, pārliecinieties, vai [x] avatāri / ir rakstāmi. Pirms turpiniet, lūdzu, izlabojiet.");
define("ADLAN_195", "Vecā mape tiek pārvietota uz dublēšanas direktoriju");
define("ADLAN_CL_2", "Lietotāji");
define("ADLAN_CL_3", "Saturs");
define("ADLAN_CL_4", "Koms");
define("ADLAN_CL_5", "Faili");
define("ADLAN_CL_6", "Rīki");
define("ADLAN_CL_7", "Spraudņi");
define("ADLAN_CL_8", "Dažādi");
define("ADLAN_LAT_1", "Jaunākās");
define("ADLAN_LAT_2", "Iesūtītie ziņu priekšmeti");
define("ADLAN_LAT_5", "Iesniegtās saites");
define("ADLAN_LAT_6", "Ziņotie foruma raksti");
define("ADLAN_LAT_7", "Faila augšupielādes");
define("ADLAN_LAT_8", "Pastāv nemodificēti administratora ziņojumi");
define("ADLAN_LAT_9", "Komentāri kas gaida apstiprinājumu");
define("ADLAN_ERR_3", "Publiskās augšupielādes direktorijās ir viens vai vairāki faili, kas nav jūsu atļauto augšupielādes failu tipu sarakstā. Iespējams, ka uzbrucējs to varēja ievietot, un ja tas būtu jānoņem [b]nekavējoties[/b]. Jums [b]nedrīkst[/b] atvērt šos failus, jo tas var izpildīt jebkuru ļaunprātīgo kodu, ko fails varētu saturēt; piem., neatveriet tos pārlūkprogrammā.

Ja jūs atzīstat šos failus par likumīgiem, iespējams, ka kāda iemesla dēļ faila tips vairs neatbilst atļauto failu tipu sarakstam, un jums tas būs jāpievieno (sk. Admin => augšupielādes). Jūs nedrīkstat ļaut augšupielādēt .html, .txt utt kā uzbrucējs, var augšupielādēt šāda veida failu, kas ietver ļaunprātīgu javascript. Protams, jums nevajadzētu arī ļaut augšupielādēt .php failus vai cita veida izpildāmo skriptu.

Zemāk ir saraksts ar failiem, kas potenciāli varētu būt ļaunprātīgi:");
define("LAN_CREATE", "Izveidot");
define("LAN_MANAGE", "Pārvaldīt");
define("LAN_UPDATE", "Atjaunot");
define("LAN_UPDATES", "Atjauninajumi");
define("LAN_INSTALLED", "Uzstādīts");
define("LAN_LAST_UPDATED", "Pēdējoreiz atjaunots");
define("LAN_UPDATE_AVAILABLE", "Pieejama atjaunināšana");
define("LAN_ADD", "pievienot");
define("LAN_REMOVE", "Noņemt");
define("LAN_ADD_MORE", "Pievienot vairāk");
define("LAN_MULTIPLE_CHOICE", "Vairāku izvēli");
define("LAN_SAVE", "Saglabāt");
define("LAN_SAVED", "Saglabāts");
define("LAN_SETSAVED", "Jūsu iestatījumi ir saglabāti");
define("LAN_NOCHANGE_NOTSAVED", "Nekas nav mainīts - nav saglabāts");
define("LAN_CONFIRMDEL", "Lūdzu, apstipriniet, ka vēlaties dzēst");
define("LAN_ERRORS", "Kļūdas");
define("LAN_MESSAGES", "Ziņojumi");
define("LAN_DATA", "Datums");
define("LAN_OPTIONS", "Iespējas");
define("LAN_BASIC_OPTIONS", "Pamata Iespējas");
define("LAN_PREFS", "Prekferences");
define("LAN_DELETED", "Veiksmīgi dzēsts");
define("LAN_UPDATED", "Veiksmīgi atjaunināts");
define("LAN_CREATED", "Veiksmīgi izveidots");
define("LAN_CREATED_FAILED", "Izveide neveiksmīga");
define("LAN_DELETED_FAILED", "Dzēšana Neveiksmīga");
define("LAN_UPDATED_FAILED", "Atjaunināt neveiksmīgi");
define("LAN_NO_CHANGE", "Nekas nav atjaunināts, jo izmaiņas netika veiktas.");
define("LAN_TRY_AGAIN", "Lūdzu mēģiniet vēlreiz.");
define("LAN_NEVER", "Nekad");
define("LAN_PRUNE", "Apgriezt");
define("LAN_RESET", "Atiestatīt");
define("LAN_CLEAR", "Nodzēst");
define("LAN_ADD_ALL", "Pievienot Visu");
define("LAN_CLEAR_ALL", "Nodzēst Visu");
define("LAN_CLICK_HERE", "Noklikšķiniet šeit");
define("LAN_UNKNOWN", "Nezināms");
define("LAN_ALL", "Viss");
define("LAN_IMPORT", "Importēt");
define("LAN_NOTWRITABLE", " nav rakstāms, vispirms ir nepieciešams CHMOD 777 failu vai mapi.");
define("LAN_NOTREADABLE", "Nav nolasāms");
define("LAN_MISSING", "Trūkst");
define("LAN_UNUSED", "Neizmantots");
define("LAN_SESSION", "Sesija");
define("LAN_TOOLTIP", "Rīka padoms");
define("LAN_TIME", "Laiks");
define("LAN_EMPTY", "Vēl nav datu ierakstu datu bāzē");
define("LAN_EXISTING", "Esošie ieraksti");
define("LAN_DEFAULT_TABLE_DATA", "Noklusējuma tabulas datu pievienošana tabulai:");
define("LAN_CONFDELETE", "Apstipriniet dzēšanu");
define("LAN_PLUGIN", "Spraudnis");
define("LAN_PLUGIN_FOLDER", "Spraudņu mape");
define("LAN_THEMES", "Motīvi");
define("LAN_THEME", "Motīvs");
define("LAN_CORE", "Kodols");
define("LAN_LATEST_e107_NEWS", "Jaunākās e107 ziņas");
define("LAN_WEBSITE_STATUS", "Vietnes statuss");
define("LAN_STATS", "Statistika");
define("LAN_ONLINE", "Tiešsaistē");
define("LAN_ORDER", "Secība");
define("LAN_ASC", "Augošs");
define("LAN_DESC", "Dilstošs");
define("LAN_SELECT", "Izvēlieties");
define("LAN_ADMIN", "Admins");
define("LAN_ROOT", "Sakne");
define("LAN_LINE", "Līnija");
define("LAN_SHORTCODES", "Īsie kodi");
define("LAN_DISPLAYOPT", "Labot attēlošanas Opcijas");
define("LAN_DATESTAMP", "Datuma zīmogs");
define("LAN_TIMESTAMP", "Laikspiedols");
define("LAN_PAGE", "LAPA");
define("LAN_AGENT", "AĢENTS");
define("LAN_LANG", "Val.");
define("LAN_APPROVE", "Apstiprināt");
define("LAN_OPTIONAL", "neobligāti");
define("LAN_INACTIVE", "Neaktīvs");
define("LAN_ACTIVATE", "Aktivizēt");
define("LAN_ACCEPT", "Pieņemt");
define("LAN_PASSWORD_WARNING", "Ir ļoti ieteicams [mainīt paroles kodēšanu] uz PHP noklusējuma. (Lietotājvārda laikā paroles hashes tiks automātiski jaunināts.)");
define("LAN_PENDING", "Gaida");
define("LAN_SUBMITTED", "Iesniegts");
define("LAN_POSTED_BY_X", "Publicēja [x] [y]");
define("LAN_VIEW_ALL", "Apskatīt visus");
define("LAN_BAN", "Bani");
define("LAN_PATH", "Ceļšs");
define("LAN_UPLOAD", "Augšupielāde");
define("LAN_UPLOADS", "Augšupielādes");
define("LAN_UPLOAD_IMAGES", "Augšupielādēt attēlus");
define("LAN_UPLOAD_FILES", "Augšupielādēt failus");
define("LAN_UPLOAD_ADDFILE", "Pievienot citu failu");
define("LAN_UPLOAD_CONFIRM", "Visas nesaglabātās izmaiņas šajā lapā tiks zaudētas. Turpināt?");
define("LAN_UPLOAD_777", "Mape ir pazudusi vai nav rakstāma, pirms augšupielādēšanas jums nepieciešams CHMOD 777 šādā mapē:");
define("LAN_UPLOAD_SERVEROFF", "Šī opcija ir atspējota, jo servera faila augšupielāde nav iespējota");
define("LAN_WIDTH", "Platums");
define("LAN_HEIGHT", "Augstums");
define("LAN_ON", "Ieslēgts");
define("LAN_OFF", "Izslēgts");
define("LAN_DISABLED", "Atspējots");
define("LAN_ENABLED", "Iespējots");
define("LAN_BOOL_REVERSE", "Mainīt");
define("LAN_DETAILS", "Detaļās");
define("LAN_NOT_AVAILABLE", "Nav pieejams");
define("LAN_AUTO_GENERATED", "Auto ģenerēts");
define("LAN_AUTOMATION", "Automatizācija");
define("LAN_PRESET_CONFIRMSAVE", "Vai saglabāt pašreizējās formas vērtības kā šīs lapas noklusējumu?");
define("LAN_CONFIGURE", "Konfigurēt");
define("LAN_NOPERMISSION", "nav atļauju");
define("LAN_NO_ADMIN_PERMISSION", "Jums nav administratora atļaujas [x]");
define("LAN_CREDITS", "Kredīti");
define("LAN_NEWVERSION", "e107 v[x] Pieejams");
define("LAN_CHECKALL", "Atzīmēt visu");
define("LAN_UNCHECKALL", "Neatzīmet visu");
define("LAN_DELCHECKED", "Dzēst atzīmētos");
define("LAN_USERCLASS", "Lietotāja klase");
define("LAN_MANAGER", "Pārvaldnieks");
define("LAN_HELP", "Palīdzība");
define("LAN_CUSTOM", "Pielāgots");
define("LAN_MENULAYOUT", "Izvēlnes izkārtojums");
define("LAN_MEDIAMANAGER", "Multivides pārvaldnieks");
define("LAN_MOREINFO", "Vairāk informācijas...");
define("LAN_COMMENTMAN", "Komentāru pārvaldnieks");
define("LAN_FILTER", "Filtrēt");
define("LAN_STATUS", "Statuss");
define("LAN_URL", "url");
define("LAN_OWNER", "Īpašnieks");
define("LAN_PURCHASE", "Pirkums");
define("LAN_DOWNLOADING", "Lejupielāde");
define("LAN_ID", "Id");
define("LAN_TEST", "Tests");
define("LAN_VISIBILITY", "Redzamība");
define("LAN_VISIBLE_TO", "Redzams uz");
define("LAN_PARENT", "Vecāks");
define("LAN_ICON", "Ikona");
define("LAN_LOADING", "Ielādē...");
define("LAN_RUN", "palaist");
define("LAN_SEFURL", "PAŠA URL");
define("LAN_COPY", "kopēt");
define("LAN_KEYWORDS", "Atslēgvārdi");
define("LAN_TEMPLATE", "Veidne");
define("LAN_TEMPLATES", "Veidnes");
define("LAN_CATEGORIES", "Kategorijas");
define("LAN_DEMO_FORBIDDEN", "Demonstrācijas režīmā šīs lapas izmaiņas nav iespējamas.");
define("LAN_COPYRIGHT", "Autortiesības");
define("LAN_MANAGEPERMS", "Pārvaldīt atļaujas");
define("LAN_PING", "Pings");
define("LAN_START", "Sākt");
define("LAN_END", "Beigt");
define("LAN_PREVIEW", "Priekšskatījums");
define("LAN_CREATE_CATEGORY", "Izveidot kategoriju");
define("LAN_CREATE_ITEM", "Izveidojiet vienumu");
define("LAN_SECURITYL_0", "Meklējat nepatikšanas (nav)");
define("LAN_SECURITYL_5", "Līdzsvarots");
define("LAN_SECURITYL_7", "Augsts");
define("LAN_SECURITYL_9", "paranoisks");
define("LAN_SECURITYL_10", "Ārprātīgs");
define("LAN_BATCH_LABEL_SELECTED", "Ar atlasīto...");
define("LAN_BATCH_LABEL_PREFIX", "Mainīt");
define("LAN_LABEL_LABEL_SELECTED", "Filtrēt");
define("LAN_FILTER_LABEL_PREFIX", "Filtrēt pēc");
define("LAN_FILTER_LABEL_DISPLAYALL", "Attelot visu");
define("LAN_FILTER_LABEL_CLEAR", "Notīrīt filtru");
define("LAN_FILTER_LABEL_TYPED", "(drukāti)");
define("LAN_UI_NOPID_ERROR", "Nav iestatīts [b]Primārais ID[/b]");
define("LAN_UI_BATCHDEL_ERROR", "Partijas dzēšana nav atļauta!");
define("LAN_UI_404_BODY_ERROR", "pieprasītā lapa netika atrasta!");
define("LAN_UI_404_TITLE_ERROR", "Lapa nav atrasta");
define("LAN_UI_404_METHOD_ERROR", "Darbība [x] nav atrasta!");
define("LAN_UI_403_BODY_ERROR", "Piekļuve pieprasītajai lapai ir noraidīta.");
define("LAN_UI_403_TITLE_ERROR", "Pieeja noliegta");
define("LAN_UI_FORM_METHOD_ERROR", "FATĀLA KĻŪDA: lauka nosaukums [x] nav atļauts. Lūdzu, pārdēvējiet atslēgu [x] uz kaut ko citu savā lauku masīvā un datu bāzes tabulā (ja nepieciešams).");
define("LAN_UNKNOWN_ERROR", "Nezināma kļūda");
define("LAN_SQL_ERROR", "SQL Kļūda");
define("LAN_UI_BATCH_UPDATE_SUCCESS", "[x] iestatīts [y] ierakstam (-iem).");
define("LAN_UI_BATCH_REVERSED_SUCCESS", "[x] ieraksti ir veiksmīgi mainīti.");
define("LAN_UI_BATCH_BOOL_SUCCESS", "[x] ieraksti veiksmīgi atjaunināti.");
define("LAN_UI_BATCH_DEATTACH_SUCCESS", "[x] noņemts no [y] ieraksta (-iem).");
define("LAN_UI_EDIT_LABEL", "Atjaunināt ierakstu #[x]");
define("LAN_UI_CREATE_LABEL", "Izveidot jaunu ierakstu");
define("LAN_UI_PREF_LABEL", "Iestatījumi");
define("LAN_UI_DELETE_LABEL", "Apstipriniet dzēšanu");
define("LAN_UI_DELETE_WARNING", "Jūs gatavojaties dzēst [x] ierakstus. Lūdzu, apstipriniet, lai turpinātu");
define("LAN_UI_BATCH_CREATELINK", "Izveidot saiti");
define("LAN_UI_DELETED", "[x] ieraksts (-i) veiksmīgi dzēsts!");
define("LAN_UI_DELETED_FAILED", "[x] ieraksti nav atrasti un nav izdzēsti!");
define("LAN_UI_FILE_DELETED", "[x] fails veiksmīgi izdzēsts!");
define("LAN_UI_FILE_DELETED_FAILED", "Nevar izdzēst [x]! Lūdzu, noņemiet failu manuāli.");
define("LAN_UI_BATCH_EXPORT", "Eksportēt");
define("LAN_UI_USING_DATABASE_TABLE", "Izmantojot [x] datubāzes tabulu");
define("LAN_UI_TOTAL_RECORDS", "Kopējie ieraksti: [x]");
define("LAN_UI_FILTER_PAST_HOUR", "Pagājušā stundā");
define("LAN_UI_FILTER_PAST_24_HOURS", "Pēdējo 24 stundu laikā");
define("LAN_UI_FILTER_PAST_WEEK", "Pagājušā nedēļa");
define("LAN_UI_FILTER_PAST_MONTH", "Pagājušais mēnesis");
define("LAN_UI_FILTER_PAST_YEAR", "Pagājušais Gads");
define("LAN_USER_MANAGEALL", "Pārvaldiet visu lietotāja, lietotāja klases un paplašinātā lietotāja lauka iestatījumus");
define("LAN_USER_LIST", "Lietotāju saraksts");
define("LAN_USER_QUICKADD", "Biedra Ātrā pievienošana");
define("LAN_USER_NOT_FOUND", "Lietotājs nav atrasts.");
define("LAN_USER_PRUNE", "Apgriezt Lietotājus");
define("LAN_USER_OPTIONS", "Lietotāja opcijas");
define("LAN_USER_RANKS", "Lietotāju ranks");
define("LAN_CONTROL_PANEL", "[x]'s Vadības panelis");
define("LAN_CUSTOM_URL", "Pielāgots URL");
define("LAN_CUSTOM_URL_DISABLED", "Atspējots vai ievadiet pielāgotu URL");
define("LAN_GENERAL", "Vispārējs");
define("LAN_GEN_PW", "Ģenerē paroli");
define("LAN_DISPL_PW", "Parādiet paroli");
define("LAN_WILL_OVERWRITE_SEF", "Tas pārraksta jūsu esošo PAŠA URL.");
define("LAN_CAPTION", "Virsraksts");
define("LAN_LIMIT", "Limiti");
define("LAN_BASIC", "Pamata");
define("LAN_EXTENDED", "Pagarināts");
define("LAN_ADVANCED", "Uzlabots");
define("LAN_DISPLAY", "Attēlots");
define("LAN_FOLDER", "Mape");
define("LAN_PERSONALIZE_ICONS", "Personalizējiet ikonas");
define("LAN_PERSONALIZE_MENUS", "Personalizējiet izvēlnes");
define("LAN_LATEST_COMMENTS", "Jaunākie komentāri");
define("LAN_COMMENTS_ALLOWED", "Komentāri ir atļauti");
define("LAN_PERSONALIZE", "Personalizējiet");
define("LAN_SETTINGS_NOT_SAVED_NO_CHANGES_MADE", "Iestatījumi nav saglabāti, jo izmaiņas netika veiktas.");
define("LAN_DASHBOARD_LAYOUT", "Informācijas paneļa izkārtojums");
define("LAN_UNAVAILABLE", "Nav pieejams");
define("LAN_UNINSTALL", "Atinstalēt");
define("LAN_NO_LABEL_PROVIDED", "Nav norādīta marķējuma");
define("LAN_NOT_FOUND", "Nav atrasts!");
define("LAN_FIELD", "Lauks");
define("LAN_MAINTENANCE", "Apkope");
define("LAN_RETURN_TO_FRONT_PANEL", "Atgriezieties sākuma panelī");
define("LAN_CHANGE_LANGUAGE", "Mainīt Valodu");
define("LAN_NEWER_VERSION_OF_X", "Lejupielādei ir pieejama jaunāka [x] [y] versija.");
define("LAN_SUBJECT", "Priekšmets");
define("LAN_ITEM", "Vienums");
define("LAN_LOCK", "Slēgts");
define("LAN_SYSTEM_USER", "Sistēmas lietotājs");
define("LAN_ENGINE", "Dzinējs");
define("LAN_SOURCE", "Avots");
define("LAN_UPGRADING", "Jaunināšana?");
define("LAN_DONT_SHOW_AGAIN", "Nerādīt vēlreiz");
define("LAN_ERROR_CONNECTION", "Nevar izveidot savienojumu ar atjauninājumiem. Lūdzu, pārbaudiet ugunsmūri un / vai interneta pieslēgumu.");
define("LAN_UI_X_CANT_EQUAL_Y", "[x] nevar būt tāds pats kā [y]");
define("LAN_UI_VIEW_GRID_LABEL", "Režģa skats");
define("LAN_UI_VIEW_LIST_LABEL", "Saraksta skats");
define("LAN_CHECKING_FOR_UPDATES", "Pārbaude par atjauninājumiem");
define("LAN_UI_FILTER_NEXT_HOUR", "Nākamā stunda");
define("LAN_UI_FILTER_NEXT_24_HOURS", "Nākamās 24 stundas");
define("LAN_UI_FILTER_NEXT_WEEK", "Nākamnedēļ");
define("LAN_UI_FILTER_NEXT_MONTH", "Nākammēnes");
define("LAN_UI_FILTER_NEXT_YEAR", "Nākamgad");
define("LAN_UI_FILTER_IS_EMPTY", "Ir tukšs");
define("LAN_RECALCULATE_COMMENT_COUNT", "Pārrēķiniet komentāru skaitu");
define("LAN_SUCC_RECALCULATE_COMMENT_COUNT", "Komentāru skaits veiksmīgi pārrēķināts!");
define("LAN_NO_RESULTS_FOUND", "Nekas nav atrasts.");
