<?php
/*
 * e107 website system
 *
 * Copyright (C) 2008-2017 e107 Inc (e107.org)
 * Released under the terms and conditions of the
 * GNU General Public License (http://www.gnu.org/licenses/gpl.txt)
 *
 */
define("CORE_DATE_ORDER", "d.m.y");
define("LAN_MAILOUT_01", "No vārda");
define("LAN_MAILOUT_02", "No e-pasta adreses");
define("LAN_MAILOUT_03", "kam");
define("LAN_MAILOUT_04", "CC");
define("LAN_MAILOUT_05", "BCC");
define("LAN_MAILOUT_06", "Temats");
define("LAN_MAILOUT_07", "Pielikums");
define("LAN_MAILOUT_08", "Nosūtīt e-pastu");
define("LAN_MAILOUT_09", "Sūtīt formātu");
define("LAN_MAILOUT_10", "Lietotājs abonējis");
define("LAN_MAILOUT_11", "Ievietot mainīgos");
define("LAN_MAILOUT_12", "Visi lietotāji");
define("LAN_MAILOUT_13", "Visi nepārbaudītie lietotāji");
define("LAN_MAILOUT_14", "redzamais vārds");
define("LAN_MAILOUT_15", "Izejošais Pasts");
define("LAN_MAILOUT_16", "Lietotājvārds");
define("LAN_MAILOUT_17", "Reģistrēšanās saite");
define("LAN_MAILOUT_18", "Lietotāja ID");
define("LAN_MAILOUT_19", "Nav norādīta mērķa e-pasta adrese");
define("LAN_MAILOUT_20", "Sendmail-ceļš");
define("LAN_MAILOUT_21", "Lielapjoma pasta ieraksti");
define("LAN_MAILOUT_22", "Pašlaik nav saglabātu ierakstu");
define("LAN_MAILOUT_23", "lietotājklase:");
define("LAN_MAILOUT_24", "e-pasts (-i) ir gatavi sūtīt");
define("LAN_MAILOUT_25", "Lielapjoma pasta kontrole");
define("LAN_MAILOUT_26", "pauzēt lielapjoma pasta sūtīšanu ik pēc");
define("LAN_MAILOUT_27", "e-pastus par");
define("LAN_MAILOUT_28", "Saglabāt izmaiņas");
define("LAN_MAILOUT_29", "sekundes");
define("LAN_MAILOUT_30", "Lietots galvenokārt ar SMTP keepalive. Pauzi, kas pārsniedz 30 sekundes, var izraisīt pārlūka taimautu");
define("LAN_MAILOUT_31", "Atgūt e-pasta apstrāde");
define("LAN_MAILOUT_33", "Ienākošā pasta serveris");
define("LAN_MAILOUT_34", "Konta (lietotāja) nosaukums");
define("LAN_MAILOUT_36", "Dzēst atgrieztos pastus pēc pārbaudes");
define("LAN_MAILOUT_37", "Turpināt");
define("LAN_MAILOUT_38", "Atcelt");
define("LAN_MAILOUT_39", "E-pasts");
define("LAN_MAILOUT_41", "pirms pasta sūtīšanas no šīs lapas.");
define("LAN_MAILOUT_43", "Lietotājvārds");
define("LAN_MAILOUT_44", "lietotāja ieeja");
define("LAN_MAILOUT_45", "Lietotāja e-pasts");
define("LAN_MAILOUT_46", "Lietotāja atbilstība");
define("LAN_MAILOUT_47", "satur");
define("LAN_MAILOUT_48", "vienāds");
define("LAN_MAILOUT_51", "Tēma");
define("LAN_MAILOUT_52", "Pēdējais mod");
define("LAN_MAILOUT_53", "Administratori");
define("LAN_MAILOUT_54", "Pašam");
define("LAN_MAILOUT_55", "Lietotāju Klase");
define("LAN_MAILOUT_56", "pēdējais apmeklējums");
define("LAN_MAILOUT_57", "Lielapjoma SMTP e-pasta ziņojumu sūtīšana blokos");
define("LAN_MAILOUT_67", "E-pastu nevarēja nosūtīt. Lūdzu, izskatiet savus SMTP iestatījumus vai izvēlieties citu pasta metodi un mēģiniet vēlreiz.");
define("LAN_MAILOUT_68", "Reģistrētie lietotāji");
define("LAN_MAILOUT_69", "spēles, pēc");
define("LAN_MAILOUT_70", "dublikātus noņemt".);
define ("LAN_MAILOUT_71", "kopējais e-pasta sūtīšana");
define("LAN_MAILOUT_71", "Kopējie e-pasta ziņojumi, lai nosūtītu");
define("LAN_MAILOUT_72", "zvana zvans");
define("LAN_MAILOUT_73", "Nav reģistrēšanās");
define("LAN_MAILOUT_74", "Tikai reģistrēšana (nav nosūtīt)");
define("LAN_MAILOUT_75", "Log un nosūtīt");
define("LAN_MAILOUT_76", "Iekļaut e-pasta informāciju žurnālā");
define("LAN_MAILOUT_77", "e-pasta adreses avoti");
define("LAN_MAILOUT_78", "Mailshot statuss");
define("LAN_MAILOUT_79", "Nav e-pastu, lai parādītu");
define("LAN_MAILOUT_81", "E-pasts ir veiksmīgi nosūtīts, lūdzu, pārbaudiet iesūtni.");
define("LAN_MAILOUT_82", "Nosūtītās vēstules");
define("LAN_MAILOUT_83", "Pasta iet");
define("LAN_MAILOUT_84", "pasta ID");
define("LAN_MAILOUT_85", "Sākotnējs");
define("LAN_MAILOUT_86", "Atkārtoti nosūtīt");
define("LAN_MAILOUT_87", "SMTP serveris");
define("LAN_MAILOUT_88", "SMTP lietotājvārds");
define("LAN_MAILOUT_89", "SMTP parole");
define("LAN_MAILOUT_90", "SMTP funkcijas");
define("LAN_MAILOUT_91", "POP pirms SMTP");
define("LAN_MAILOUT_92", "ssl");
define("LAN_MAILOUT_93", "TLs");
define("LAN_MAILOUT_94", "(Izmantot SSL par gmail / googlemail)");
define("LAN_MAILOUT_95", "Izmantot VERP lielapjoma nosūtīšanai");
define("LAN_MAILOUT_97", "Mailer rezultāti");
define("LAN_MAILOUT_98", "Bāreņu ieraksti");
define("LAN_MAILOUT_99", "Apstiprināt atkārtotu mailshot");
define("LAN_MAILOUT_100", "Ziņojums");
define("LAN_MAILOUT_101", "e-pasta detaļa");
define("LAN_MAILOUT_102", "mailshot detaļa");
define("LAN_MAILOUT_103", "Sūtīšanas mēģinājumu rezultāti");
define("LAN_MAILOUT_104", "Nav mēģinājums nosūtīt vai kļūdu saglabāšanas rezultāts");
define("LAN_MAILOUT_105", "Sīkāka informācija par 10 neveiksmēm");
define("LAN_MAILOUT_106", "E-pastu nevarēja nosūtīt. Šķiet, ka jūsu serveris nav pareizi konfigurēts, lai nosūtītu e-pastus, lūdzu, mēģiniet vēlreiz, izmantojot SMTP, vai sazinieties ar saviem saimniekiem un lūdziet viņus pārbaudīt to sendmail / e-pasta servera iestatījumus.");
define("LAN_MAILOUT_107", "pie");
define("LAN_MAILOUT_108", "Rezultāts");
define("LAN_MAILOUT_109", "Rādīt detaļu");
define("LAN_MAILOUT_110", "Nosūtīt testa e-pastu");
define("LAN_MAILOUT_111", "E-pasta sadaļa (nav nosūtīta)");
define("LAN_MAILOUT_112", "Nosūtīt testa e-pastu uz");
define("LAN_MAILOUT_113", "Pārbaudīt e-pastu no");
define("LAN_MAILOUT_114", "Šis ir pārbaudes e-pasts, šķiet, ka jūsu e-pasta iestatījumi darbojas labi! [br] [br] Atzinības [br] no e107 vietnes sistēmas.");
define("LAN_MAILOUT_115", "Masveida e-pasta nosūtīšanas metode");
define("LAN_MAILOUT_116", "Ja neesat pārliecināts, atstājiet kā php");
define("LAN_MAILOUT_117", "pabeigt");
define("LAN_MAILOUT_118", "Noklikšķiniet uz 'turpināt', lai sāktu e-pasta sūtīšanu. Noklikšķiniet uz 'atcelt' , lai pārtrauktu palaišanu. Pēc pabeigšanas atlasiet citu lapu.");
define("LAN_MAILOUT_119", "Tikai reģistrēšana, ar kļūdām");
define("LAN_MAILOUT_120", "Konta veids");
define("LAN_MAILOUT_121", "Standarta POP3");
define("LAN_MAILOUT_122", "POP3, TLS atspējots");
define("LAN_MAILOUT_123", "POP3 ar TLS");
define("LAN_MAILOUT_124", "Imap");
define("LAN_MAILOUT_125", "Tikai teksts");
define("LAN_MAILOUT_126", "teksts un HTML");
define("LAN_MAILOUT_127", "Iekļaut tēmu");
define("LAN_MAILOUT_128", "Nosūtīt kļūdu");
define("LAN_MAILOUT_129", "Derīguma termiņš");
define("LAN_MAILOUT_130", "Izveides datums");
define("LAN_MAILOUT_131", "sūtīšana sākusies");
define("LAN_MAILOUT_132", "sūtīšana pabeigta");
define("LAN_MAILOUT_134", "Prioritāte");
define("LAN_MAILOUT_136", "izejas statuss");
define("LAN_MAILOUT_137", "Pasta Ref");
define("LAN_MAILOUT_138", "e-pasta statuss");
define("LAN_MAILOUT_139", "Datums aktīvs");
define("LAN_MAILOUT_140", "Saņēmēja e-pasts");
define("LAN_MAILOUT_141", "Saņēmēja vārds");
define("LAN_MAILOUT_142", "Saņēmēja lietotāja ID");
define("LAN_MAILOUT_143", "Saņēmēja ref.");
define("LAN_MAILOUT_144", "Atlēkušas");
define("LAN_MAILOUT_145", "Jauns e-pasts saglabāts");
define("LAN_MAILOUT_146", "Kļūda saglabājot e-pastu");
define("LAN_MAILOUT_147", "E-pasts atjaunināts");
define("LAN_MAILOUT_148", "Lietotāja vērtības");
define("LAN_MAILOUT_149", "Nosūtītāja e-pasts");
define("LAN_MAILOUT_150", "Nosūtītāja vārds");
define("LAN_MAILOUT_151", "Kopēt uz");
define("LAN_MAILOUT_152", "Tukšu kopija uz");
define("LAN_MAILOUT_153", "Pielikumi");
define("LAN_MAILOUT_154", "Sūtīt formātu");
define("LAN_MAILOUT_155", "atlasītāji");
define("LAN_MAILOUT_156", "Maksimālais e-pasta ziņojumu skaits, lai nosūtītu vienu plānotāja atzīmi");
define("LAN_MAILOUT_157", "Vērtība būs atkarīga no vairākiem faktoriem, ieskaitot to, cik bieži jūsu pasta rindas plānotāja darbs tiek aktivizēts, un ātrumu, kādā jūsu ISP pieņems izejošo pastu. Katru reizi nulle tiek iztīrīta no rindas");
define("LAN_MAILOUT_158", "Sūtīt tūlīt");
define("LAN_MAILOUT_159", "Aizturēt e-pastu");
define("LAN_MAILOUT_160", "Atcelt sūtīt");
define("LAN_MAILOUT_161", "SVARĪGI! Šis fails, šķiet, nepastāv");
define("LAN_MAILOUT_162", "SVARĪGI! Jums ir nepieciešams padarīt šo failu izpildāmu");
define("LAN_MAILOUT_163", "rediģēt / sūtīt pastu");
define("LAN_MAILOUT_164", "E-pasta informācija nav atrasta");
define("LAN_MAILOUT_165", "Apstiprināt dzēst tālāk saglabāto e-pastu, ieskaitot visus adresātu ierakstus");
define("LAN_MAILOUT_166", "Vispārējā kļūda, dzēšot pasta ref: [x]");
define("LAN_MAILOUT_167", "Kļūda, dzēšot pasta satura ref: [x]");
define("LAN_MAILOUT_168", "Pasta saturs dzēsts ref: [x]");
define("LAN_MAILOUT_169", "Kļūda pasta adresātu dzēšanai ref: [x]");
define("LAN_MAILOUT_170", "Dzēsts [y] saņēmējiem pasta ref: [x]");
define("LAN_MAILOUT_171", "Apstiprināt e-pasta dzēšanu");
define("LAN_MAILOUT_172", "Mail Type / Status");
define("LAN_MAILOUT_173", "Saņēmēji");
define("LAN_MAILOUT_174", "Drošības pārbaude neizdodas: [x] [z]");
define("LAN_MAILOUT_175", "Pirms");
define("LAN_MAILOUT_176", "vienāds ar");
define("LAN_MAILOUT_177", "Pēc");
define("LAN_MAILOUT_178", "Pēdējās vietnes apmeklējums");
define("LAN_MAILOUT_179", "Apstiprināt e-pasta sūtīšanu");
define("LAN_MAILOUT_180", "Atlases kritēriji:");
define("LAN_MAILOUT_181", "Rādīt saņēmējus");
define("LAN_MAILOUT_182", "Tidy datubāzu tabulas");
define("LAN_MAILOUT_183", "Kļūda datu bāzē");
define("LAN_MAILOUT_184", "Datubāze tidied");
define("LAN_MAILOUT_185", "e-pasta adreses, kas tiek pievienotas, lai nosūtītu rindu");
define("LAN_MAILOUT_186", "Vispārējā kļūda, ievietojot pasta ref: [x] aizturēts");
define("LAN_MAILOUT_187", "E-pasts [x] aizturēts");
define("LAN_MAILOUT_188", "Vispārēja kļūda nosūtot e-pasta ref: [x]");
define("LAN_MAILOUT_189", "Testa adrese");
define("LAN_MAILOUT_190", "Izveidot / sūtīt pastu");
define("LAN_MAILOUT_191", "Saglabāti e-pasta ziņojumi");
define("LAN_MAILOUT_192", "Pabeigts Mailshots");
define("LAN_MAILOUT_193", "Gaida zvani");
define("LAN_MAILOUT_194", "Pasākumi");
define("LAN_MAILOUT_200", "Nav norādīts neviens tēma");
define("LAN_MAILOUT_201", "Nav nozīmīgu e-pasta datu");
define("LAN_MAILOUT_202", "Nav e-pasta tekstā teksta");
define("LAN_MAILOUT_203", "Nav norādīts sūtītāja vārds");
define("LAN_MAILOUT_204", "Nav norādīta sūtītāja e-pasta adrese");
define("LAN_MAILOUT_205", "E-pasta sūtīšanas formāta kļūda");
define("LAN_MAILOUT_206", "Nepareizs pasta ID [[x]) norādīts");
define("LAN_MAILOUT_207", "Veidnes ielādes kļūda");
define("LAN_MAILOUT_208", "Veidņu pārvēršanas kļūda");
define("LAN_MAILOUT_211", "Nosūtīts");
define("LAN_MAILOUT_212", "Neizdevās");
define("LAN_MAILOUT_213", "Atlēkušas");
define("LAN_MAILOUT_214", "Lai nosūtītu");
define("LAN_MAILOUT_215", "Saglabāts");
define("LAN_MAILOUT_216", "Koda kļūda");
define("LAN_MAILOUT_217", "Notika");
define("LAN_MAILOUT_218", "atcelts");
define("LAN_MAILOUT_219", "daļēji");
define("LAN_MAILOUT_220", "E-pasta ID [x] atcelts");
define("LAN_MAILOUT_221", "Kļūda, atceļot e-pastu ar ID [x]");
define("LAN_MAILOUT_222", "Default e-pasta formāts");
define("LAN_MAILOUT_223", "(izmanto dažiem sistēmas ģenerētiem e-pasta ziņojumiem)");
define("LAN_MAILOUT_224", "Inc. attēli");
define("LAN_MAILOUT_225", "Iekļaut attēlus e-pastā");
define("LAN_MAILOUT_226", "[x] nobriedušo saņēmēju ieraksts (-i) ir noņemts");
define("LAN_MAILOUT_227", "Svītrots [x] ieraksti no [y]");
define("LAN_MAILOUT_228", "[x] korekcijas anomālijas mail_content; ieraksti: [y]");
define("LAN_MAILOUT_229", "E-pasta ID [x] aizturēts");
define("LAN_MAILOUT_230", "Kļūda, saglabājot e-pastu ar ID [x]");
define("LAN_MAILOUT_231", "Atgrieztie e-pasta ziņojumi - apstrādes metode");
define("LAN_MAILOUT_232", "Nav");
define("LAN_MAILOUT_233", "automātiskās apstrādes skripts");
define("LAN_MAILOUT_234", "Pasta konts");
define("LAN_MAILOUT_235", "(Jūsu serverim jānosūta vai" caurule "no iepriekšējās e-pasta adreses uz iepriekš minēto skripta ceļu).");
define("LAN_MAILOUT_236", "Pēdējā atlēciena apstrāde");
define("LAN_MAILOUT_237", "Kopsavilkuma skaitītāji atjaunināti [x] e-pastos");
define("LAN_MAILOUT_238", "agrākais nosūtīšanas laiks");
define("LAN_MAILOUT_239", "Pēdējais nosūtīšanas laiks");
define("LAN_MAILOUT_240", "Paziņot man, kad tas ir pabeigts");
define("LAN_MAILOUT_241", "(tas ir papildus standarta e107 paziņošanas opcijām)");
define("LAN_MAILOUT_242", "Papildu opcijas (tikai nosūtot)");
define("LAN_MAILOUT_243", "Paziņot");
define("LAN_MAILOUT_244", "E-pasts nosūtīts:");
define("LAN_MAILOUT_245", "Pārbaudīt automātisku bounces");
define("LAN_MAILOUT_246", "Ja atzīmēts, jums būs jāaktivizē uzdevums plānotājā");
define("LAN_MAILOUT_247", "E-pasta informācija:");
define("LAN_MAILOUT_248", "pabeigšanas statuss:");
define("LAN_MAILOUT_249", "Sūtīt rezultātus:");
define("LAN_MAILOUT_250", "--- paziņojuma beigu datums ---");
define("LAN_MAILOUT_251", "Kopēt un rediģēt");
define("LAN_MAILOUT_252", "Vai dažādas datu konsekvences pārbaudes, koriģē skaitļus, izdzēš pagaidu datus");
define("LAN_MAILOUT_253", "Neviens adresāts nav atrasts - pārbaudiet datu bāzes korupciju");
define("LAN_MAILOUT_254", "Skatīt veidlapu e-pastu");
define("LAN_MAILOUT_255", "Veidotais e-pasts, ID:");
define("LAN_MAILOUT_256", "Atgriezties");
define("LAN_MAILOUT_257", "Izveidota veidne");
define("LAN_SEND", "Nosūtīt");
define("LAN_HOLD", "Notika");
define("LAN_MAILOUT_260", "Lietotāja tips");
define("LAN_MAILOUT_261", "SMTP ports");
define("LAN_MAILOUT_262", "Veidņu priekšskatījums");
define("LAN_MAILOUT_263", "Kopējie saņēmēji");
define("LAN_MAILOUT_264", "Iegult Media");
define("LAN_MAILOUT_265", "Gaida");
define("LAN_MAILOUT_266", "Max Aktīvs");
define("LAN_MAILOUT_267", "Izveidot publiskās / privātās atslēgas");
define("LAN_MAILOUT_268", "Tikai izstrādes režīmā");
define("LAN_MAILOUT_269", "Nosūtīt vēlāk");
define("LAN_MAILOUT_270", "pārbaudīt SMTP savienojumu");
define("LAN_MAILOUT_271", "Autentifikācija neizdevās, izmantojot lietotājvārdu ([x]) un paroli ([y]):");
