<?php
/*
 * Copyright (C) 2008-2013 e107 Inc (e107.org), Licensed under GNU GPL (http://www.gnu.org/licenses/gpl.txt)
 *
 * Admin Language File
 *
*/
define("LAN_IMA_M_01", "multivides bibliotēka");
define("LAN_IMA_M_02", "multivides augšupielāde / importēšana");
define("LAN_IMA_M_03", "multivides kategorijas");
define("LAN_IMA_M_04", "Izveidot kategoriju");
define("LAN_IMA_M_05", "Avatari");
define("LAN_IMA_001", "modifikācija nav atļauta");
define("LAN_IMA_002", "Nav pietiekami daudz atmiņas, lai pagrieztu");
define("LAN_IMA_003", "Pagriezts");
define("LAN_IMA_004", "izmēra maiņa");
define("IMALAN_1", "Iespējot attēla rādīšanu");
define("IMALAN_2", "Parādīt attēlus, tas tiks piemērots vietnei (komentāri, čatara kaste utt.) attēliem, kas ievietoti, izmantojot [img] bbcode");
define("IMALAN_3", "izmēra maiņas metode");
define("IMALAN_4", "Metode, ko izmanto, lai mainītu attēlus, vai nu GD1 / 2 bibliotēka, vai ImageMagick");
define("IMALAN_5", "Ceļš uz ImageMagick (ja izvēlēts)");
define("IMALAN_6", "Pilns ceļš uz ImageMagick Convert lietderību");
define("IMALAN_7", "Attēla iestatījumi");
define("IMALAN_8", "Atjaunināt attēlu iestatījumus");
define("IMALAN_9", "Attēla iestatījumi atjaunināti");
define("IMALAN_10", "Attēlu displeja klase");
define("IMALAN_11", "Ierobežot lietotājus, kuri var apskatīt attēlus (ja ir iespējots iepriekš)");
define("IMALAN_12", "Atspējot attēlu metodi");
define("IMALAN_13", "Kas jādara ar attēliem, ja attēla displejs ir atspējots");
define("IMALAN_14", "Rādīt attēla URL");
define("IMALAN_15", "nerādīt neko");
define("IMALAN_18", "Augšupielādēti Avataru attēli");
define("IMALAN_20", "Nekas nav mainīts");
define("IMALAN_21", "Lietots pēc");
define("IMALAN_22", "attēls netiek izmantots");
define("IMALAN_23", "Avatari");
define("IMALAN_24", "Fotogrāfija");
define("IMALAN_25", "Noklikšķiniet šeit, lai izdzēstu visus neizmantotos attēlus");
define("IMALAN_26", "attēls (-i) svītrots");
define("IMALAN_28", "izdzēsts");
define("IMALAN_29", "Bez attēliem");
define("IMALAN_36", "Apstiprināt avataru lielumu un piekļuvi");
define("IMALAN_37", "Avatara apstiprināšana");
define("IMALAN_38", "Maksimālais pieļaujamais platums");
define("IMALAN_39", "maksimālais pieļaujamais augstums");
define("IMALAN_40", "pārāk plašs");
define("IMALAN_41", "pārāk augsts");
define("IMALAN_42", "Nav atrasts");
define("IMALAN_45", "Nav atrasts");
define("IMALAN_46", "pārāk liels");
define("IMALAN_47", "Kopējie augšupielādētie attēli");
define("IMALAN_48", "Kopējie ārējie attēli");
define("IMALAN_49", "lietotāji ar attēliem");
define("IMALAN_50", "Kopā");
define("IMALAN_51", "Iemiesojums par");
define("IMALAN_52", "Ceļš uz ImageMagick šķiet nepareizs");
define("IMALAN_53", "Ceļš uz ImageMagick, šķiet, ir pareizs, bet pārveidotais fails var nebūt derīgs");
define("IMALAN_54", "instalēta GD versija:");
define("IMALAN_55", "Nav instalēts");
define("IMALAN_56", "Noklikšķiniet, lai atlasītu");
define("IMALAN_57", "Attēls pārāk liels - noklikšķiniet, lai palielinātu");
define("IMALAN_62", "Pamatojums");
define("IMALAN_65", "Nekas nav atrasts");
define("IMALAN_66", "Faila Nosaukums");
define("IMALAN_68", "Aizvērt");
define("IMALAN_69", "mape");
define("IMALAN_70", "atrodama ne-sistēmas mape!");
define("IMALAN_72", "ikonas");
define("IMALAN_73", "sīktēlu kvalitāte");
define("IMALAN_74", "Uzstādīt to pēc iespējas zemāk, pirms kvalitātes zudums ir acīmredzams. Maksimāli 100");
define("IMALAN_75", "Avataru platums");
define("IMALAN_76", "Avatāru attēli tiks ierobežoti ar šiem izmēriem (pikseļos)");
define("IMALAN_77", "Avatars Augums");
define("IMALAN_78", "Vispārīgi");
define("IMALAN_79", "Resize-Image-izmēri");
define("IMALAN_80", "Aktivizēt ūdenszīmi");
define("IMALAN_81", "Visiem attēliem ar platumu vai augstumu, kas ir lielāks par šo vērtību, mainīšanas laikā tiks piešķirts ūdenszīme.");
define("IMALAN_82", "Ūdenszīme teksts");
define("IMALAN_83", "izvēles ūdenszīmju teksts");
define("IMALAN_84", "Ūdenszīme Fonts");
define("IMALAN_85", "Izvēles ūdenszīmju fons. Augšupielādēt vairāk .ttf fontu uz / fontu mapi jūsu motīvu direktorijā.");
define("IMALAN_86", "Ūdenszīme izmērs");
define("IMALAN_87", "fonta lielums pst");
define("IMALAN_88", "Ūdenszīmju novietojums");
define("IMALAN_89", "Ūdenszīme");
define("IMALAN_90", "Ūdenszīmju marža");
define("IMALAN_91", "attālums, ka ūdenszīme parādīsies no attēla malas.");
define("IMALAN_92", "Ūdenszīme Krāsa");
define("IMALAN_93", "Ūdenszīmes krāsa, piem., 000000");
define("IMALAN_94", "ŪdenszīmeĒnas-Krāsa");
define("IMALAN_95", "ūdenszīmes zīmes ēna, piemēram, ffffff");
define("IMALAN_96", "Ūdenszīmju necaurredzamība");
define("IMALAN_97", "Ievadiet skaitli no 1 līdz 100");
define("IMALAN_98", "Noklusējuma YouTube konts");
define("IMALAN_99", "Lieto Media-Manager Youtube pārlūks. Ievadiet konta nosaukumu, piem., e107inc");
define("IMALAN_100", "Rādīt saistītos videoklipus");
define("IMALAN_101", "Rādīt video informāciju");
define("IMALAN_102", "Parādīt slēgtās parakstus pēc noklusējuma");
define("IMALAN_103", "Izmantot modestu zīmolu");
define("IMALAN_104", "Padarīt YouTube bbcode atsaucīgu");
define("IMALAN_105", "Attēlu mainīšana multivides importēšanas laikā");
define("IMALAN_106", "Atstājiet tukšu, lai atspējotu");
define("IMALAN_107", "Nevarēja radīt ceļu no augšupielādes datiem");
define("IMALAN_108", "Nevarēja pārvietot failu no [x] uz [y]");
define("IMALAN_109", "Nevarēja iegūt ceļu");
define("IMALAN_110", "ceļš");
define("IMALAN_111", "Nevarēja noteikt mime tipa ([x]). Augšupielāde neizdevās.");
define("IMALAN_112", "Nevarēja izveidot mapi ([x]).");
define("IMALAN_113", "Jaunas multivides skenēšana (attēli, video, faili) mapē:");
define("IMALAN_114", "Nav atrasta multivide! Lūdzu, augšupielādējiet dažus failus.");
define("IMALAN_115", "Nosaukums (iekšējai lietošanai)");
define("IMALAN_116", "paraksts (redzams publiski)");
define("IMALAN_118", "Mime tips");
define("IMALAN_119", "faila lielums");
define("IMALAN_120", "Izmēri");
define("IMALAN_121", "Priekšskatījums");
define("IMALAN_122", "[x] nevarēja pārdēvēt. Pārbaudiet failu perms.");
define("IMALAN_123", "Importēt kategorijās:");
define("IMALAN_124", "Importēt atlasītos failus");
define("IMALAN_125", "Dzēst atlasītos failus");
define("IMALAN_126", "Lūdzu, pārbaudiet vismaz vienu failu.");
define("IMALAN_127", "Nevarēja iegūt faila informāciju no:");
define("IMALAN_128", "Media importēšana:");
define("IMALAN_129", "Jūs gatavojaties dzēst [x] ierakstus un <strong> VISI ATBILSTOŠI FILES </ strong>! Lūdzu, apstipriniet, lai turpinātu!");
define("IMALAN_130", "Iepriekšējā lapa");
define("IMALAN_131", "Nākamā lapa");
define("IMALAN_132", "Tags / Atslēgvārdi");
define("IMALAN_133", "Apakšā pa labi");
define("IMALAN_134", "Apakšā pa kreisi");
define("IMALAN_135", "labais labais");
define("IMALAN_136", "augšējā kreisajā stūrī");
define("IMALAN_137", "Centrs");
define("IMALAN_138", "Labais");
define("IMALAN_139", "pa kreisi");
define("IMALAN_140", "Augšup");
define("IMALAN_141", "Apakšā");
define("IMALAN_142", "Flīze");
define("IMALAN_143", "attēls");
define("IMALAN_144", "Fails");
define("IMALAN_145", "No datora");
define("IMALAN_146", "Nav HTML5 atbalsta.");
define("IMALAN_147", "No attālinātās vietas");
define("IMALAN_148", "Attēla / faila URL");
define("IMALAN_149", "Sākt augšupielādi");
define("IMALAN_150", "Augšupielādēt failu");
define("IMALAN_151", "Izvēlieties no bibliotēkas");
define("IMALAN_152", "Izskats");
define("IMALAN_153", "Lietošana attēlā");
define("IMALAN_154", "Neizmantots");
define("IMALAN_155", "Ielu attēla priekšatlases mape");
define("IMALAN_156", "Dzēst visus neizmantotos attēlus");
define("IMALAN_157", "Teksta plūsma");
define("IMALAN_158", "Robeža-Pa Kreisi");
define("IMALAN_159", "Robeža-Pa Labi");
define("IMALAN_160", "Robeža No augšas");
define("IMALAN_161", "Robeža No Apakšas");
define("IMALAN_162", "Parādīšana [x] - [y] no [z] attēliem.");
define("IMALAN_163", "Video.");
define("IMALAN_164", "Izdzēstās ikonas no Media-Manager");
define("IMALAN_165", "Bez attēliem");
define("IMALAN_166", "Augšupielādēt attēlus vai failus");
define("IMALAN_167", "Nav faila");
define("IMALAN_168", "Noklikšķiniet uz iemiesojuma, lai to mainītu");
define("IMALAN_169", "Nav pieejami avatari");
define("IMALAN_170", "Izvēlieties šo iemiesojumu");
define("IMALAN_171", "Tikai Admin-Notice: mape");
define("IMALAN_172", "ir tukšs. Augšupielādēt dažus noklusējuma avataru attēlus uz šo mapi, lai lietotāji varētu izvēlēties Avatars no.");
define("IMALAN_173", "Nav atrasts neviens multivides īpašnieks");
define("IMALAN_174", "Youtube meklēšana prasa (bezmaksas) YouTube v3 api taustiņu. [br] Šī atslēga nav nepieciešama, ja vien jūs nevēlaties veikt atslēgvārdu, atskaņošanas sarakstu vai kanālu meklēšanu. [br] Youtube video URL ievadīšana tieši iepriekš minētais lodziņš joprojām darbosies bez api taustiņa. [br] [x]");
define("IMALAN_175", "Meklēt Youtube. Ielīmējiet šeit jebkuru YouTube vietrādi konkrētu videoklipu / atskaņošanas sarakstu / kanālu");
define("IMALAN_176", "Radās problēma satveršanas failu");
define("IMALAN_177", "Noklikšķiniet šeit, lai iegūtu papildinformāciju un ievadītu savu api taustiņu");
define("IMALAN_178", "Avatars Folder (lietotāja izvēles)");
define("IMALAN_179", "Avatars Folder (privāts)");
define("IMALAN_180", "0 baitu fails atrasts:");
define("IMALAN_181", "Lūdzu, noņemiet pirms turpināšanas.");
define("IMALAN_182", "Konvertēt uz JPEG importa laikā");
define("IMALAN_183", "PNG un GIF faili tiks automātiski pārveidoti jpeg formātā (izņemot ikonas)");
define("IMALAN_184", "noklusējuma attēla izmēri");
define("IMALAN_185", "Maksimālais augstums pikseļos");
