<?php
/*
 * Copyright e107 Inc e107.org, Licensed under GNU GPL (http://www.gnu.org/licenses/gpl.txt)
 *
 * Language file - Search
 *
*/
define("PAGE_NAME", "Meklēt");
define("LAN_140", "Dalībnieki");
define("LAN_192", "Visas kategorijas");
define("LAN_193", "Pasākumu kalendārs");
define("LAN_194", "Visas kategorijas");
define("LAN_195", "Meklēšana");
define("LAN_196", "atbilstība");
define("LAN_197", "Lejupielādes");
define("LAN_198", "Sakritības nav atrastas");
define("LAN_199", "Meklēt:");
define("LAN_416", "Jums ir jāpiesakās, lai piekļūtu šai lapai");
define("LAN_417", "Meklēšanas vienumiem jābūt vismaz [x] rakstzīmēm.");
define("LAN_418", "Citas lapas");
define("LAN_SEARCH_1", "Atzīmēt visu");
define("LAN_SEARCH_2", "Noņemiet atzīmi no visas izvēles");
define("LAN_SEARCH_3", "Publicēts");
define("LAN_SEARCH_4", "Sakritība atrodama ziņu virsrakstā");
define("LAN_SEARCH_5", "Sakritība atrodama jaunumu tekstā");
define("LAN_SEARCH_6", "Sakritība atrodams pagarinātā ziņu tekstā");
define("LAN_SEARCH_7", "Iesūtījis");
define("LAN_SEARCH_8", "uz");
define("LAN_SEARCH_9", "Bez nosaukuma");
define("LAN_SEARCH_11", "Rezultāti");
define("LAN_SEARCH_12", "no");
define("LAN_SEARCH_13", "iekšā");
define("LAN_SEARCH_14", "Kategorija:");
define("LAN_SEARCH_15", "Autors:");
define("LAN_SEARCH_17", "Atvainojiet, meklēšana ir ierobežota ar vienu meklēšanu katru reizi");
define("LAN_SEARCH_18", " sekundes.");
define("LAN_SEARCH_19", "Meklēt:");
define("LAN_SEARCH_20", "Nepieciešama autorizācija");
define("LAN_SEARCH_21", "Jums nav tiesību skatīt šo lapu.");
define("LAN_SEARCH_22", "Visas teritorijas");
define("LAN_SEARCH_23", "Uzlabotā vaicājuma forma");
define("LAN_SEARCH_24", "Jābūt vārdam (-iem)");
define("LAN_SEARCH_25", "Nedrīkst būt vārds (-i)");
define("LAN_SEARCH_26", "Precīza frāze");
define("LAN_SEARCH_27", "Vārds (-i), kas sākas ar");
define("LAN_SEARCH_28", "Visai nav izvērstas meklēšanas");
define("LAN_SEARCH_29", "Pamata");
define("LAN_SEARCH_30", "Progresīvs");
define("LAN_SEARCH_31", "Nav detalizētas meklēšanas");
define("LAN_SEARCH_32", "Šādi vārdi tika izslēgti no meklēšanas");
define("LAN_SEARCH_33", "Šis vārds tika izslēgts no meklēšanas");
define("LAN_SEARCH_34", "Jaunāki nekā");
define("LAN_SEARCH_35", "Vecāki par");
define("LAN_SEARCH_36", "Jebkurā laikā");
define("LAN_SEARCH_37", "Viena diena");
define("LAN_SEARCH_38", "Divas dienas");
define("LAN_SEARCH_39", "Trīs dienas");
define("LAN_SEARCH_40", "Viena nedēļa");
define("LAN_SEARCH_41", "Divas nedēļas");
define("LAN_SEARCH_42", "Trīs nedēļas");
define("LAN_SEARCH_43", "Viens mēnesis");
define("LAN_SEARCH_44", "Divus mēnešus");
define("LAN_SEARCH_45", "Trīs mēneši");
define("LAN_SEARCH_46", "Pusgads");
define("LAN_SEARCH_47", "Viens gads");
define("LAN_SEARCH_48", "Divus gadus");
define("LAN_SEARCH_49", "Trīs gadi");
define("LAN_SEARCH_50", "Datums publicēta");
define("LAN_SEARCH_51", "Visas kategorijas");
define("LAN_SEARCH_52", "Sakritība ");
define("LAN_SEARCH_53", "Vesels priekšmets");
define("LAN_SEARCH_54", "Tikai virsraksts");
define("LAN_SEARCH_55", "Meklēt ziņu kategorijā");
define("LAN_SEARCH_56", "Visas ziņu kategorijas");
define("LAN_SEARCH_57", "Komentāri tika publicēti vietnē");
define("LAN_SEARCH_58", "Visas teritorijas");
define("LAN_SEARCH_59", "Visi komentāri");
define("LAN_SEARCH_60", "Komentāri tika publicēti vietnē");
define("LAN_SEARCH_61", "Autors");
define("LAN_SEARCH_62", "Datums pievienots");
define("LAN_SEARCH_63", "Meklēt kategorijā");
define("LAN_SEARCH_64", "Visas lejupielādes kategorijas");
define("LAN_SEARCH_65", "Lejupielādes");
define("LAN_SEARCH_66", "Pievienošanas datums");
define("LAN_SEARCH_67", "Visi lejupielādes dati");
define("LAN_SEARCH_69", "Atbilstība");
define("LAN_SEARCH_70", "Nosūtīts, lai lejupielādētu vienumu");
define("LAN_SEARCH_71", "Iesūtīts atbildē uz ziņu vienumu");
define("LAN_SEARCH_72", "Paraksts");
define("LAN_SEARCH_73", "Paraksts nav.");
define("LAN_SEARCH_74", "Pievienojies uz");
define("LAN_SEARCH_75", "Meklēšanas veids");
define("LAN_SEARCH_76", "Iesūtīts lapā");
define("LAN_SEARCH_77", "Publicēts profila lapā");
define("LAN_SEARCH_98", "Jaunumi");
define("LAN_SEARCH_201", "Lūdzu, no jauna definējiet savu meklēšanas vaicājumu");
define("LAN_SEARCH_202", "Pārslēgt uzlaboto režīmu");
